<script language="javascript">
  $(function() {
  $("#empCmb").change(function(){

  $("#custText").val(this.value)    ;
  });
  });
</script>

<script type="text/javascript">
  $(function() {

  $("#dialog-modal").hide();

  $("#addon").click(function() {
  $("#dialog-modal").dialog({
  height: 260,
  width: 500,
  modal: true,
  resizable: false,
  buttons: {
  'Ok': function() {
  $(this).dialog('close');
  },
  Cancel: function() {
  $(this).dialog('close');
  }
  }


  });
  });
  });

</script>

<div id="dialog-modal" title="Quick Status Update">
  <form name="addon_form">


    <div class="form_row">
      <div class="form_label">
        Quick Supplier: <span class="required">*</span>
      </div>
      <div class="form_field">
        <select>
          <option class=""  value="--Select--">--Select--</option>
          <option class=""  value="--Select--">Smith</option>
          <option class=""  value="--Select--">WBS</option>
          <option class=""  value="--Select--">DB</option>
          <option class=""  value="--Select--">Tacco</option>
          <option class=""  value="--Select--">Blain</option>
          <option class=""  value="--Select--">Cuff</option>
        </select>
            </div>
    </div>
    <div class="form_row">
      <div class="form_label">
        Status: <span class="required">*</span>
      </div>
      <div class="form_field">
        <select>
          <option class=""  value="--Select--">--Select--</option>
          <option class=""  value="--Select--">Condemn</option>
          <option class=""  value="--Select--">Un-Condemn</option>
          <option class=""  value="--Select--">Retained</option>
          <option class=""  value="--Select--">Un-Retained</option>
        </select>
      </div>
    </div>
  </form>
</div>


<form method="post" action="<?php echo $this->seoUrl("/mps/compliance/index")?>">
<input type="hidden" value="1" name="search" />
<div> <?php echo $this->flashMessages()?> </div>
  <table width="100%" cellspacing="0" cellpadding="0">
 
  <tr>
    <td align="left"> <table class="from_table" border="0" cellspacing="0" cellpadding="0">
    	
    	<tr>
          <td align="right" class="form_tab_lebel" valign="top"><?php echo $this->puts($this->form->cowid->getLabel()); ?> </td>
          <td align="left" class="form_tab_input" valign="top">
            <?php echo $this->form->cowid; ?>
      </td>
          <td align="right"  class="form_tab_lebel" valign="top"><?php echo $this->puts($this->form->supplier->getLabel()); ?></td>
          <td align="left" valign="top">
            <?php echo $this->form->supplier; ?>
          </td>
        </tr>
      <tr>
      <td align="right" class="form_tab_lebel" valign="top">&nbsp;</td>
      <td align="left" class="form_tab_input search_button"  valign="top" >
        <input type="submit" class="search" value="Search">
          <img class="search_img" src="<?php echo $this->cdnUri()?>/images/search_img.png" alt="">
      </td>
      <td align="right"  class="form_tab_lebel" valign="top">&nbsp;</td>
      <td align="left" class="form_tab_input" valign="top">&nbsp;</td>
      <td align="right"  class="form_tab_lebel" valign="top">&nbsp;</td>
      <td align="left" class="form_tab_input" valign="top"></td>
    </tr>
      <tr>
        <td align="left" class="form_tab_input" colspan="4" valign="top" style="padding:23px 0 0 0;"><input type="button" id="addon" class="gray_button_dark"  value="Quick  Status Update"></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
    	</table>
    </td>
  </tr>
</table>
</form>


<?php if (count($this->paginator)): ?>
 <?php
        $sno=0;
        $page=$this->paginator->getCurrentPageNumber();
        $items_per_page=$this->paginator->getItemCountPerPage(); 
        if($page>1)
        {
                $sno=$items_per_page*$page - $items_per_page ; 	
        }
        ?>
        <?php 
            
           echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));
              
        ?>


<div class="gird_box">
  <div class="scroll-pane">
    <table class="grid_table" border="0"  cellspacing="0" cellpadding="0">
      <tr>
        <th align="left" width="60"><?php echo $this->puts("Seq. No.")?></th>
        <th align="left" width="90"><?php echo $this->puts("Cow ID")?></th>
        <th align="left" width="90"><?php echo $this->puts("Breed")?><img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
        <th align="left" width="90"><?php echo $this->puts("Type")?><img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
        <th align="left" width="110"><?php echo $this->puts("Color")?><img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
        <th align="left" width="110"><?php echo $this->puts("Knock Date")?><img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
        <th align="left" width="140"><?php echo $this->puts("Supplier")?><img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
        <th align="left" width="120"><?php echo $this->puts("Status")?><img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
        <th align="left" width="150"><?php echo $this->puts("Action")?> </th>
      </tr>

      
      <?php 
        foreach ($this->paginator as $item): ?>
        <?php $sno++; $id=$item->id;?>
      
      
      <tr class="package_row1">
        <td align="left"><?php echo $item->sequence_no; ?></td>
        <td align="left"><?php echo $item->id; ?></td>
        <td align="left"><?php echo $item->breed; ?></td>
        <td align="left"><?php echo $item->type; ?></td>
        <td align="left"><?php echo $item->color; ?></td>
        <td align="left"><?php echo $item->knocked_date; ?></td>
        <?php $suppObj = new Admin_Model_Supplier();
              $supplier_info = $suppObj->fetchRow("id = '$item->supplier_id'");
        
        ?>
        <td align="left"><?php echo $supplier_info->username; ?></td>
        <td align="left" valign="middle" class="image">
            <select class="s1">

            <option class=""  value="--Select--">Condemn</option>
            <option class=""  value="--Select--">Un-Condemn</option>
            <option class=""  value="--Select--">Retained</option>
            <option class=""  value="--Select--">Un-Retained</option>

          </select>
         </td>
        <td align="left" class="image">
          <a href=" " style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/edit.png" border="0" title="Edit"/></a>
          <a href=" "  style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/accept.png" border="0" title="Accept"/></a>
          <a href=" "  style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/print.png" border="0" title="Print"/></a>
        </td>
      </tr>
      
<?php endforeach; ?>
      
    </table>
  </div>
</div>

<?php 
      echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));
      ?>
    <?php else : ?>
    <p>No result found</p>
    <?php endif;?>
    


<script type="text/javascript">


  // Script For Grid Starts //
  $(document).ready(function () {
  //row click
  $('tr.package_row1').click(function (event) {
  $('tr.package_row1').toggleClass('active', false);
  $(this).toggleClass('active', true);
  });
  // table Width
  var tblWidth = 0;
  $('.grid_table tr:first').children().each(function (index) {
  tblWidth = tblWidth + parseInt($(this).attr('width'));
  });
  //$(".grid_table").css("width", tblWidth);
  });

  $('.grid_table tr').find('td:last').addClass('last')
  $('.grid_table tr').find('th:last').addClass('last')
  // Script For Grid Ends //



  // Script For Scroll Panel Starts //
  /*$(function(){
  $('.scroll-pane').jScrollPane({showArrows: true});
  });*/
  // Script For Scroll Panel Ends //


  // Script For Tabs Panel Starts //
  $(function () {
  $('#tabs').tabs();
  });
  // Script For Tabs Panel Ends //

  $(".s1").dropdownchecklist({ emptyText: "Please select ...", width: 110 });
  //$(".s1").dropdownchecklist({ firstItemChecksAll: true, explicitClose: '...close' , width: 110 }); //Jitendra

</script>