<form id="login_form" action="<?php echo $this->seoUrl("/default/auth/forgot-password")?>" method="post">
<?php if($this->msg==""){?>
    <?php echo $this->form->email;?>
    <img class="keyboard" src="<?php echo $this->cdnUri()?>/images/keyboard.png" alt="">
    <input id="btnLogin" name="btnLogin" type="button" value="Submit" onclick='submitForm()'>
<?php }else{
    echo $this->msg;
}
?>
    </form>
<script type="text/javascript">
$('input[placeholder], textarea[placeholder]').placeholder();
$('#btnLogin').click(function() {
  $('#login_form').submit();
});
</script>
