<form>
       
    <table class="from_table" border="0" cellspacing="0" cellpadding="0" width="100%">
  <tr>
    <td align="right" class="form_tab_lebel" valign="top"><?php echo $this->puts("Select Supplier:")?></td>
    <td align="left" class="form_tab_input" valign="top"><select id="empCmb">
                <option value="-- Select --">-- Select --</option>
              <option value="-- Select --">Brown Dairy </option>
              <option value="-- Select --">Jeff Smith  </option>
            </select></td>
    <td align="right"  class="form_tab_lebel" valign="top"><?php echo $this->puts("Select P.O:")?></td>
    <td align="left" class="form_tab_input" valign="top"><select>
              <option value="-- Select --">-- Select --</option>
              <option value="-- Select --">12665</option>
              <option value="-- Select --">12666</option>
  </select></td>
    <td align="right" class="form_tab_lebel" valign="top"><?php echo $this->puts("Note:")?></td>
    <td align="left" class="form_tab_input" valign="top">
      <input type="text" value="">
    </td>
  </tr>

    
  <tr>
    
    <td align="left" class="form_tab_input" colspan="4" valign="top" style="padding:23px 0 0 0;"><input type="button" class="gray_button_dark"  value="<?php echo $this->puts("Un-Do This P.O.#")?>"></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td align="right" class="form_tab_lebel" valign="top" style="padding:23px 0 23px 0;"><input type="button" style="margin:0 10px 19px 0;" value="<?php echo $this->puts("Finish & Print")?>" class="yellow_button"></td>
   

  </tr>
  
</table>

  </form>
      <div class="gird_box">
        <div class="scroll-pane">
          <table class="grid_table" style="margin:0 0 15px 0;" border="0"  cellspacing="0" cellpadding="0">
            <tr>
              <th align="left" width="80"><?php echo $this->puts("Seq No.")?></th>
              <th align="left" width="80"><?php echo $this->puts("Lot No.")?></th>
              <th align="left" width="80"><?php echo $this->puts("Cow ID")?></th>
              <th align="left" width="100"><?php echo $this->puts("Cow Weight")?></th>
              <th align="left" width="80"><?php echo $this->puts("Price/lb ($)")?></th>
              <th align="left" width="100"><?php echo $this->puts("Price/Cow ($)")?></th>
              <th align="left" width="120"><?php echo $this->puts("Breed")?></th>
              <th align="left" width="120"><?php echo $this->puts("Type")?></th>
              <th align="left" width="120"><?php echo $this->puts("Status")?></th>
              <th align="left" width="120"><?php echo $this->puts("Date In")?></th>
              <th align="left" width="140"><?php echo $this->puts("Condemn")?></th>
              <th align="left" width="120"><?php echo $this->puts("Action")?></th>
            </tr>
            <tr class="package_row1">
              <td align="left">
               1
              </td>
              <td align="left">
                12500
              </td>

              <td align="left">
                19070
              </td>
              <td align="left">618.00</td>
              <td align="left">$10.00</td>
              <td align="left">$120.00</td>
              <td align="left">Cow</td>
              <td align="left">Holstein</td>
              <td align="left"> </td>
              <td align="left">01/09/2012 </td>
              <td align="left">Weighed</td>
              <td align="left" class="image">
                <a href=" " style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/edit.png" border="0" title="Edit"/></a>
                <a href=" "  style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/accept.png" border="0" title="Accept"/></a>
              </td>
            </tr>
             <?php for($i=1;$i<20;$i++){?> 
            <tr class="package_row1">
              <td align="left"><?php echo $i+1; ?></td>
              <td align="left">1250<?php echo $i; ?></td>
             
              <td align="left">1907<?php echo $i; ?></td>
              <td align="left">618.00</td>
              <td align="left">$10.00</td>
              <td align="left">$120.00</td>
              <td align="left">Cow</td>
              <td align="left">Holstein</td>
              <td align="left"> </td>
              <td align="left">01/09/2012 </td>
              <td align="left">Weighed</td>
              <td align="left" class="image">
                <a href=" " style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/edit.png" border="0" title="Edit"/></a>
                <a href=" "  style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/accept.png" border="0" title="Accept"/>
                </a>
              </td>
            </tr>
             <?php } ?>
           
          </table>
        </div>
      </div>
      <!--<div class="result_box">Results: 1-20 of 50</div>
      <div class="paging">
        <ul>
          <li>
            <a href="#" class="arrow-first" title="First">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-first.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-prev" title="Previous">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-prev.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="active" title="Page 1">1</a>
          </li>
          <li>
            <a href="#" title="Page 2">2</a>
          </li>
          <li>
            <a href="#" title="Page 3">3</a>
          </li>
          <li>
            <a href="#" class="arrow-next" title="Next">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-next.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-last" title="Last">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-last.png" alt="">
            </a>
          </li>
        </ul>
      </div>-->
      <script type="text/javascript">
		
		
        // Script For Grid Starts //
		$(document).ready(function(){
			//row click
			$('tr.package_row1').click(function (event) {
								$('tr.package_row1').toggleClass('active', false);
								$(this).toggleClass('active', true);
								});
			// table Width
			var tblWidth=0;
			$('.grid_table tr:first').children().each(function(index) {
									tblWidth = tblWidth + parseInt($(this).attr('width'));
									});
			$(".grid_table").css("width", tblWidth);
		});

		$('.grid_table tr').find('td:last').addClass('last')
		$('.grid_table tr').find('th:last').addClass('last')
		// Script For Grid Ends //



		// Script For Scroll Panel Starts //
		$(function(){
		$('.scroll-pane').jScrollPane({showArrows: true});
		});
		// Script For Scroll Panel Ends //


		// Script For Tabs Panel Starts //
			$(function(){
				$('#tabs').tabs();
			});
		// Script For Tabs Panel Ends //
        
     </script>