<?php
$this->headScript()->appendFile("/js/ui.dropdownchecklist-1.4-min.js");
$this->headScript()->appendFile("/js/ui.dropdownchecklist.js");
//$this->headScript()->appendFile("/js/jquery-1.6.1.min.js");
$this->headScript()->appendFile("/js/jquery-ui-1.8.13.custom.min.js");
$this->headLink()->appendStylesheet('/js/ui.dropdownchecklist.standalone.css');
$this->headLink()->appendStylesheet('/js/ui.dropdownchecklist.themeroller.css');
$this->headLink()->appendStylesheet('/js/smoothness-1.8.13/jquery-ui-1.8.13.custom.css');
?>
<form>


 <table class="from_table" border="0" cellspacing="0" cellpadding="0">
    
  <tr>
    <td align="right" class="form_tab_lebel" valign="top">Breed</td>
    <td align="left" class="form_tab_input" valign="top"> 
   <select name="type">
            <option value="--Select--">--Select--</option>
            <option value="--Select--">Angus</option>
            <option value="--Select--">Holstein</option>
         </select>
    </td>
            
    <td align="right" class="form_tab_lebel" valign="top">Type:</td>
    <td align="left" class="form_tab_input" valign="top">
        <select name="type">
            <option value="--Select--">--Select--</option>
            <option value="--Select--">Angus</option>
            <option value="--Select--">Holstein</option>
         </select>
    </td>
    <td align="right"  class="form_tab_lebel" valign="top">Color:</td>
    <td align="left" class="form_tab_input" valign="top">
      <select name="color">
        <option value="-- Select --">-- Select --</option>
        <option value="Smith">Red</option>
        <option value="John">Black</option>
        <option value="Mike">Gray</option>
        <option value="Smith">Yellow</option>
        <option value="John">White</option>
      </select>
    </td>
  </tr>
    
 <tr>
    <td align="right" class="form_tab_lebel" valign="top">Cow ID: </td>
    <td align="left" class="form_tab_input" valign="top"><input type="text" value="" name="cowID"/></td>
    <td align="right"  class="form_tab_lebel" valign="top">Select Supplier:</td>
    <td align="left" class="form_tab_input" valign="top"><select> <option value="-- Select --">-- Select --</option>
                <option value="Smith">Smith</option>
                <option value="John">John</option>
                <option value="Mike">Mike</option>
                <option value="Smith">Smith</option>
                <option value="John">John</option>
                <option value="Mike">Mike</option>
                <option value="Smith">Smith</option>
                <option value="John">John</option>
                <option value="Mike">Mike</option>
                <option value="Smith">Smith</option>
                <option value="John">John</option>
                <option value="Mike">Mike</option>
            </select></td>
    
    <td align="right"  class="form_tab_lebel" valign="top">Input(s):</td>
    <td align="left" valign="top">
             <select multiple="multiple" class="s1">
             
             <option class=""  value="--Select--">Auction Auction Auction</option>
             <option class=""  value="--Select--">Ear Tag</option>
             <option class=""  value="--Select--">Trich</option>
             

             </select>
              </td>
    
  </tr>
 
  
  <tr>
    <td align="right" class="form_tab_lebel" valign="top">&nbsp;</td>
    <td align="left" class="form_tab_input search_button" valign="top"><input type="button" class="search" value="Search"><img class="search_img" src="<?php echo $this->cdnUri()?>/images/search_img.png" alt=""></td>
    <td align="right"  class="form_tab_lebel" valign="top">&nbsp;</td>
    <td align="left" class="form_tab_input" valign="top">&nbsp;</td>
    <td align="right"  class="form_tab_lebel" valign="top">&nbsp;</td>
    <td align="left" class="form_tab_input" valign="top"></td>
  </tr>
  
</table>
    
   
      </form>
      <div class="result_box">Results: 1-20 of 50</div>
      <div class="paging">
        <ul>
          <li>
            <a href="#" class="arrow-first" title="First">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-first.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-prev" title="Previous">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-prev.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="active" title="Page 1">1</a>
          </li>
          <li>
            <a href="#" title="Page 2">2</a>
          </li>
          <li>
            <a href="#" title="Page 3">3</a>
          </li>
          <li>
            <a href="#" class="arrow-next" title="Next">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-next.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-last" title="Last">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-last.png" alt="">
            </a>
          </li>
        </ul>
      </div>
      <div class="gird_box">
        <div class="scroll-pane">
          <table class="grid_table" border="0"  cellspacing="0" cellpadding="0">
            <tr>
              <th align="left" width="60">Seq No.</th>
              <th align="left" width="90">Cow ID</th>
              <th align="left" width="90">Breed<img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
               <th align="left" width="90">Type<img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
              <th align="left" width="90">Color<img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
              <th align="left" width="100">Auction Tag<img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
              <th align="left" width="90">Ear Tag<img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
              <th align="left" width="90">Trich<img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
              <th align="left" width="120">Condemn<img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
              <th align="left" width="115">Action </th>

            </tr>
            
            <tr class="package_row1">
              <td align="left">1</td>
              <td align="left">1234</td>
            <td align="left">Bull</td>
               <td align="left">Angus</td>
               <td align="left">Red</td>
              <td align="left">XXXX</td>

              <td align="left">XXXX</td>
              <td align="left">XXX</td>
             <td align="left" valign="middle" class="image">
             <select multiple="multiple" class="s1">
             
             <option class=""  value="--Select--">Head</option>
             <option class=""  value="--Select--">Heart</option>
             <option class=""  value="--Select--">Intestines</option>
             <option class=""  value="--Select--">Gut</option>
             <option class=""  value="--Select--">Liver</option>
             <option class=""  value="--Select--">Extra Trim Hyde Affected</option>
             <option class=""  value="--Select--">Extra Trim Hyde Not Affected</option>

             </select>
              </td>
           <td align="left" class="image"><a href=" " style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/edit.png" border="0" title="Edit"/></a>  <a href=" "  style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/accept.png" border="0" title="Accept"/></a></td>
            </tr>
            <tr class="package_row1">
              <td align="left">2</td>
              <td align="left">1235</td>
            <td align="left">Bull</td>
               <td align="left">Angus</td>
               <td align="left">Red</td>
              <td align="left">XXXX</td>

              <td align="left">XXXX</td>
              <td align="left">XXX</td>
               <td align="left" class="image">
             <select multiple="multiple" class="s1">
             
             <option class=""  value="--Select--">Head</option>
             <option class=""  value="--Select--">Heart</option>
             <option class=""  value="--Select--">Intestines</option>
             <option class=""  value="--Select--">Gut</option>
             <option class=""  value="--Select--">Liver</option>
             <option class=""  value="--Select--">Extra Trim Hyde Affected</option>
             <option class=""  value="--Select--">Extra Trim Hyde Not Affected</option>

             </select>
              </td>
           <td align="left" class="image"><a href=" " style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/edit.png" border="0" title="Edit"/></a>  <a href=" "  style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/accept.png" border="0" title="Accept"/></a></td>
            </tr>
            <tr class="package_row1">
              <td align="left">3</td>
              <td align="left">1236</td>
              <td valign="middle" class="image">
             Cow
              </td>
               <td valign="middle" class="image">
              Holstein
              </td>
              <td valign="middle" class="image">
             Black
              </td>
              <td valign="middle" class="image">
              <input type="text" class="" value="XXXX" />
              </td>

               <td valign="middle" class="image">
              <input type="text" class="" value="XXXX" />
              </td>
               <td valign="middle" class="image">
              <input type="text" class="" value="XXX" />
              </td>
              <td align="left" class="image">
             <select multiple="multiple" class="s1">
             
             <option value="--Select--">Head</option>
             <option value="--Select--">Heart</option>
             <option value="--Select--">Intestines</option>
             <option value="--Select--">Gut</option>
             <option value="--Select--">Liver</option>
             <option value="--Select--">Extra Trim Hyde Affected</option>
             <option value="--Select--">Extra Trim Hyde Not Affected</option>

             </select>
              </td>
           <td align="left" class="image"><a href=" " style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/edit.png" border="0" title="Edit"/></a>  <a href=" "  style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/accept.png" border="0" title="Accept"/></a></td>
            </tr>
           
            <tr class="package_row1">
              <td align="left">4</td>
              <td align="left">1237</td>
              <td valign="middle" class="image">Cow</td>
               <td valign="middle" class="image">Holstein</td>
              <td valign="middle" class="image">Black</td>

               <td valign="middle" class="image">
             
              </td>
               <td valign="middle" class="image">
  
              </td>
              <td valign="middle" class="image"></td>
              <td align="left" class="image">
             <select multiple="multiple" class="s1">
             
             <option value="--Select--">Head</option>
             <option value="--Select--">Heart</option>
             <option value="--Select--">Intestines</option>
             <option value="--Select--">Gut</option>
             <option value="--Select--">Liver</option>
             <option value="--Select--">Extra Trim Hyde Affected</option>
             <option value="--Select--">Extra Trim Hyde Not Affected</option>

             </select>
              </td>
            <td align="left" class="image"><a href=" " style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/edit.png" border="0" title="Edit"/></a>  <a href=" "  style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/accept.png" border="0" title="Accept"/></a></td>

            </tr>
            <tr class="package_row1">
              <td align="left">
                5
              </td>
              <td align="left">1238</td>
              <td valign="middle" class="image">Cow</td>
              <td valign="middle" class="image">Holstein</td>
              <td valign="middle" class="image">Black</td>
              <td valign="middle" class="image">

              </td>
              <td valign="middle" class="image">

              </td>
              <td valign="middle" class="image">

              </td>
              <td align="left" class="image">
                <select multiple="multiple" class="s1">

                  <option value="--Select--">Head</option>
                  <option value="--Select--">Heart</option>
                  <option value="--Select--">Intestines</option>
                  <option value="--Select--">Gut</option>
                  <option value="--Select--">Liver</option>
                  <option value="--Select--">Extra Trim Hyde Affected</option>
                  <option value="--Select--">Extra Trim Hyde Not Affected</option>

                </select>
              </td>
              <td align="left" class="image">
                <a href=" " style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/edit.png" border="0" title="Edit"/></a>
                <a href=" "  style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/accept.png" border="0" title="Accept"/></a>
              </td>
            </tr>
            <tr class="package_row1">
              <td align="left">
              6
              </td>
              <td align="left">1239</td>
              <td valign="middle" class="image">Cow</td>
              <td valign="middle" class="image">Holstein</td>
              <td valign="middle" class="image">Black</td>
              <td valign="middle" class="image">

              </td>
              <td valign="middle" class="image">

              </td>
              <td valign="middle" class="image">

              </td>
              <td align="left" class="image">
                <select multiple="multiple" class="s1">

                  <option value="--Select--">Head</option>
                  <option value="--Select--">Heart</option>
                  <option value="--Select--">Intestines</option>
                  <option value="--Select--">Gut</option>
                  <option value="--Select--">Liver</option>
                  <option value="--Select--">Extra Trim Hyde Affected</option>
                  <option value="--Select--">Extra Trim Hyde Not Affected</option>

                </select>
              </td>
              <td align="left" class="image">
                <a href=" " style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/edit.png" border="0" title="Edit"/></a>
                <a href=" "  style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/accept.png" border="0" title="Accept"/></a>
              </td>
            </tr>
            <?php for($i=1;$i<15;$i++){?>
            <tr class="package_row1">
              <td align="left">
             <?php echo $i+6; ?>
              </td>
              <td align="left">
                12<?php echo $i+39; ?>
              </td>
              
              <td valign="middle" class="image">Cow</td>
              <td valign="middle" class="image">Holstein</td>
              <td valign="middle" class="image">Black</td>
              <td valign="middle" class="image">
               
              </td>
              <td valign="middle" class="image">
              
              </td>
              <td valign="middle" class="image">
               
              </td>
              <td align="left" class="image">
                <select multiple="multiple" class="s1">

                  <option value="--Select--">Head</option>
                  <option value="--Select--">Heart</option>
                  <option value="--Select--">Intestines</option>
                  <option value="--Select--">Gut</option>
                  <option value="--Select--">Liver</option>
                  <option value="--Select--">Extra Trim Hyde Affected</option>
                  <option value="--Select--">Extra Trim Hyde Not Affected</option>

                </select>
              </td>
              <td align="left" class="image">
                <a href=" " style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/edit.png" border="0" title="Edit"/></a>
                <a href=" "  style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/accept.png" border="0" title="Accept"/></a>
              </td>
            </tr>
            <?php } ?>
          </table>
        </div>
      </div>
      <div class="result_box">Results: 1-20 of 50</div>
      <div class="paging">
        <ul>
          <li>
            <a href="#" class="arrow-first" title="First">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-first.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-prev" title="Previous">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-prev.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="active" title="Page 1">1</a>
          </li>
          <li>
            <a href="#" title="Page 2">2</a>
          </li>
          <li>
            <a href="#" title="Page 3">3</a>
          </li>
          <li>
            <a href="#" class="arrow-next" title="Next">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-next.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-last" title="Last">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-last.png" alt="">
            </a>
          </li>
        </ul>
      </div>

       <script type="text/javascript">


        // Script For Grid Starts //
		$(document).ready(function(){
			//row click
			$('tr.package_row1').click(function (event) {
								$('tr.package_row1').toggleClass('active', false);
								$(this).toggleClass('active', true);
								});
			// table Width
			var tblWidth=0;
			$('.grid_table tr:first').children().each(function(index) {
									tblWidth = tblWidth + parseInt($(this).attr('width'));
									});
			//$(".grid_table").css("width", tblWidth);
		});

		$('.grid_table tr').find('td:last').addClass('last')
		$('.grid_table tr').find('th:last').addClass('last')
		// Script For Grid Ends //



		// Script For Scroll Panel Starts //
		/*$(function(){
		$('.scroll-pane').jScrollPane({showArrows: true});
		});*/
		// Script For Scroll Panel Ends //


		// Script For Tabs Panel Starts //
			$(function(){
				$('#tabs').tabs();
			});
		// Script For Tabs Panel Ends //

                $(".s1").dropdownchecklist({ emptyText: "Please select ...", width: 110 });
                //$(".s1").dropdownchecklist({ firstItemChecksAll: true, explicitClose: '...close' , width: 110 }); //Jitendra
                
     </script>