<form>
  <div class="form_row">
    <div class="form_label">
      Username: <span class="required">*</span>
    </div>
   <div class="form_field">
      <select>
        <option value="--Select--">--Select--</option>
        <option>User1</option>
        <option>User2</option>
        <option>User3</option>
        <option>User4</option>
        <option>User5</option>
      </select>
    </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      Password: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="password" value="">
        </div>
    <div class="form_label">
      Confirm Password: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="password" value="">
        </div>
  </div>
  
  <div class="form_row">
    <div class="form_label">&nbsp;</div>
    <div class="form_field">
      <input type="button" value="Submit">
        </div>
  </div>
</form>
