<script type="text/javascript">
function billing_shipping_same_fun(obj){
	var form_dom = document.create_customer;
	if(obj.checked == true){
		form_dom.billing_f_name.value = form_dom.shipping_f_name.value;
		form_dom.billing_l_name.value = form_dom.shipping_l_name.value;
		form_dom.billing_address.value = form_dom.shipping_address.value;
		form_dom.billing_city.value = form_dom.shipping_city.value;
		form_dom.billing_state.value = form_dom.shipping_state.value;
		form_dom.billing_zip.value = form_dom.shipping_zip.value;
                $(".billingAddress").hide();
                $("#bottomRow").removeClass("form_separate");
                
	}
	else{
		form_dom.billing_f_name.value = '';
		form_dom.billing_l_name.value = '';
		form_dom.billing_address.value = '';
		form_dom.billing_city.value = '';
		form_dom.billing_state.value = '';
		form_dom.billing_zip.value = '';
                $(".billingAddress").fadeIn(500);
                $("#bottomRow").addClass("form_separate");
                
	}
}

function copy_shipping_to_billing(obj){

	var form_dom = document.create_customer;
	if(document.getElementById('billing_shipping_same').checked == true){
		switch(obj.name){
		case 'shipping_f_name':
			form_dom.billing_f_name.value = form_dom.shipping_f_name.value;
			break;
		case 'shipping_l_name':
			form_dom.billing_l_name.value = form_dom.shipping_l_name.value;
			break;
		case 'shipping_address':
			form_dom.billing_address.value = form_dom.shipping_address.value;
			break;
		case 'shipping_city':
			form_dom.billing_city.value = form_dom.shipping_city.value;
			break;
		case 'shipping_state':
			form_dom.billing_state.value = form_dom.shipping_state.value;
			break;
		case 'shipping_zip':
			form_dom.billing_zip.value = form_dom.shipping_zip.value;
			break;
		}
	}
}
</script>

<form name="create_customer">
        <div class="form_row">
          <div class="form_label">Organization Name: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" value="">
          </div>
        </div>
        <div class="form_row form_separate">
          <!-- <div class="form_label">Password: <span class="required">*</span></div>
          <div class="form_field">
            <input type="password" value="">
          </div>
          <div class="form_label">Confirm Password: <span class="required">*</span></div>
          <div class="form_field">
            <input type="password" value="">
          </div> -->
        </div>
        <!-- <div class="form_row">
          <div class="form_label">Title: <span class="required">*</span></div>
          <div class="form_field">
            <select>
              <option value="-- Select --">-- Select --</option>
            </select>
          </div>
        </div> -->
		<div class="form_row"><div class="form_label"> <h2> Shipping Address </h2></div></div>
        <div class="form_row">
          <div class="form_label">First Name: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_f_name" onkeyup="copy_shipping_to_billing(this);">
          </div>
          <div class="form_label">Last Name: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_l_name" onkeyup="copy_shipping_to_billing(this);">
          </div>
        </div>
        <!-- <div class="form_row">
          <div class="form_label">Gender: <span class="required">*</span></div>
          <div class="form_field">
            <select>
              <option value="-- Select --">-- Select --</option>
            </select>
          </div>
        </div> -->
		<div class="form_row">
          <div class="form_label">Address: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_address" onkeyup="copy_shipping_to_billing(this);">
          </div>
          <div class="form_label">City: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_city" onkeyup="copy_shipping_to_billing(this);">
          </div>
        </div>

		<div class="form_row">
          <div class="form_label">State: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_state" onkeyup="copy_shipping_to_billing(this);">
          </div>
          <div class="form_label">Zip: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_zip" onkeyup="copy_shipping_to_billing(this);">
          </div>
        </div>

        <div class="form_row">
          <div class="form_label">Phone Number: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_phone">
          </div>
          <div class="form_label">Fax: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_fax">
          </div>
        </div>

	<div class="form_row">
          <div class="form_label">Email: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_email">
          </div>
        </div>

	<div class="form_row" id="bottomRow">
          <div class="form_label">Billing Address: <span class="required">*</span></div>
          <div class="form_field_same">
            <input type="checkbox" name="billing_shipping_same" checked="true" id="billing_shipping_same" onclick="billing_shipping_same_fun(this);"/>
              &nbsp;&nbsp;Same as Above </div>
        </div>
        <div class="billingAddress" style="display:none;">	
	 <div class="form_row"><div class="form_label"> <h2> Billing Address </h2></div></div>

	 <div class="form_row">
          <div class="form_label">First Name: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="billing_f_name">
          </div>
          <div class="form_label">Last Name: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="billing_l_name">
          </div>
        </div>
        <!-- <div class="form_row">
          <div class="form_label">Gender: <span class="required">*</span></div>
          <div class="form_field">
            <select>
              <option value="-- Select --">-- Select --</option>
            </select>
          </div>
        </div> -->
	<div class="form_row">
          <div class="form_label">Address: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="billing_address">
          </div>
          <div class="form_label">City: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="billing_city">
          </div>
        </div>

	<div class="form_row">
          <div class="form_label">State: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="billing_state">
          </div>
          <div class="form_label">Zip: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="billing_zip">
          </div>
        </div>
		
       
        </div>
         <div class="form_row">
          <div class="form_label">&nbsp;</div>
          <div class="form_field">
            <input type="button" value="Submit">
          </div>
        </div>
      </form>