<form>
  <div class="form_row">
    <div class="form_label">
      Username: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
  </div>
  <div class="form_row form_separate">
    <div class="form_label">
      Password: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="password" value="">
        </div>
    <div class="form_label">
      Confirm Password: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="password" value="">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      Organization Name: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      First Name: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
    <div class="form_label">
      Last Name: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      Address1: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
    <div class="form_label">
      Address2:
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      City: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
    <div class="form_label">
      State: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      Zip: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      Phone: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
    <div class="form_label">
      Fax: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      Email: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>

  </div>
    <div class="form_row">
        <div class="form_label">&nbsp;</div>
        <div class="form_field">
        <input type="button" value="Submit">
        </div>
    </div>
</form>