<form name="create_menu">
        <div class="form_row">
          <div class="form_label">Location Title:<span class="required">*</span></div>
          <div class="form_field">
            <input type="text" value="">
          </div>
        </div>
        
        
	<div class="form_row">
          <div class="form_label">Description: <span class="required">*</span></div>
          <div class="form_field">
              <textarea rows="5"></textarea>
          </div>
          
        </div>
       
          
     <div class="form_row">
          <div class="form_label">Tare Weight:<span class="required">*</span></div>
          <div class="form_field">
            <input type="text" value="">
          </div>
        </div>
    
       <div class="form_row">
          <div class="form_label">Is Active: <span class="required">*</span></div>
          
            <div class="form_field_same">
              <table class="from_table" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td>
                    <input name="is_active" type="radio" value="">
                  </td>
                  <td width="50">
                    Yes
                  </td>
                  <td>
                    <input name="is_active" type="radio" value="">
                  </td>
                  <td>
                    No
                  </td>
                </tr>

              </table>
              
            
           </div>
        
          </div>

		
        <div class="form_row">
          <div class="form_label">&nbsp;</div>
          <div class="form_field">
            <input type="button" value="Submit">
          </div>
        </div>
      </form>