<form>
  <div class="form_row">
    <div class="form_label">
      Username: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
  </div>
  <div class="form_row form_separate">
    <div class="form_label">
      Password: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="password" value="">
        </div>
    <div class="form_label">
      Confirm Password: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="password" value="">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      Organization Name: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      First Name: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
    <div class="form_label">
      Last Name: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      Address1: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
    <div class="form_label">
      Address2:
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      City: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
    <div class="form_label">
      State: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      Zip: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      Phone: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
    <div class="form_label">
      Fax: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      Email: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
    
  </div>
  <div class="form_row">
    <div class="form_label">
      Group: <span class="required">*</span>
    </div>
    <div class="form_field">
      <select>
        <option value="--Select--">--Select--</option>
        <option>Group1</option>
        <option>Group2</option>
        <option>Group3</option>
        <option>Group4</option>
        <option>Group5</option>
      </select>
    </div>

    <div class="form_label">
      Sub Group: <span class="required">*</span>
    </div>
    <div class="form_field">
      <select>
        <option value="--Select--">--Select--</option>
        <option>SubGroup1</option>
        <option>SubGroup2</option>
        <option>SubGroup3</option>
        <option>SubGroup4</option>
        <option>SubGroup5</option>
      </select>
    </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      Role: <span class="required">*</span>
    </div>
    <div class="form_field">
      <select>
        <option value="--Select--">--Select--</option>
        <option>Role1</option>
        <option>Role2</option>
        <option>Role3</option>
        <option>Role4</option>
        <option>Role5</option>
      </select>
    </div>
    <div class="form_label">
      Supervisor: <span class="required">*</span>
    </div>
    <div class="form_field">
      <select>
        <option value="--Select--">--Select--</option>
        <option>Arthur Edwin</option>
        <option>Mabel Edwin</option>
        <option>Supervisor3</option>
       
      </select>
    </div>
  </div>

  <div class="form_row">
    <div class="form_label">&nbsp;</div>
    <div class="form_field">
      <input type="button" value="Submit">
        </div>
  </div>
</form>