<form>
    
    
    <table class="from_table" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="right"  class="form_tab_lebel" valign="top">Location Title:</td>
    <td align="left" class="form_tab_input" valign="top"><input type="text" value=""></td>
    <td align="right"  class="form_tab_lebel" valign="top"><!-- Status: --></td>
    <td align="left" class="form_tab_input" valign="top"><!-- <input type="text" value=""> --></td>
    <td align="right" class="form_tab_lebel" valign="top"><!-- Menu ID:-->&nbsp;</td>
    <td align="left" class="form_tab_input" valign="top"><!--<input type="text" value="">-->&nbsp;</td>
  </tr>

  
  <tr>
    <td align="right" class="form_tab_lebel" valign="top">&nbsp;</td>
    <td align="left" class="form_tab_input search_button" valign="top"><input class="search" value="Search" type="button">
            <img class="search_img" src="<?php echo $this->cdnUri()?>/images/search_img.png" alt=""></td>
    <td align="right"  class="form_tab_lebel" valign="top">&nbsp;</td>
    <td align="left" class="form_tab_input" valign="top">&nbsp;</td>
    <td align="right"  class="form_tab_lebel" valign="top">&nbsp;</td>
    <td align="left" class="form_tab_input" valign="top">&nbsp;</td>
  </tr>
  
</table>

 </form>
      <div class="result_box">Results: 1-4 of 50</div>
      <div class="paging">
        <ul>
          <li>
            <a href="#" class="arrow-first" title="First">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-first.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-prev" title="Previous">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-prev.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="active" title="Page 1">1</a>
          </li>
          <li>
            <a href="#" title="Page 2">2</a>
          </li>
          <li>
            <a href="#" title="Page 3">3</a>
          </li>
          <li>
            <a href="#" class="arrow-next" title="Next">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-next.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-last" title="Last">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-last.png" alt="">
            </a>
          </li>
        </ul>
      </div>
      <div class="gird_box">
        <div class="scroll-pane">
          <table class="grid_table" width="100%" border="0"  cellspacing="0" cellpadding="0">
            <tr>
                <th align="left" width="8%">S. No</th>
                <th align="left" width="25%">Title</th>
                <th align="left" width="40%">Description</th>
                <th align="left" width="12%">Tare Weight</th>
                <th align="left" width="15%">Is Active</th>
            </tr>
            
            <tr class="package_row1">
              <td align="left">1</td>
              <td align="left">Bone</td>
              <td align="left">Description</td>
              <td align="left">50</td>
              <td align="left" class="last image"><img title="Active" src="<?php echo $this->cdnUri()?>/images/icons/active-1.png" /></td>
            </tr>
           <tr class="package_row1">
              <td align="left">2</td>
              <td align="left">Tripe</td>
              <td align="left">Description</td>
               <td align="left">60</td>
              <td align="left" class="last image"><img title="Active" src="<?php echo $this->cdnUri()?>/images/icons/active-1.png" /></td>
            </tr>
            <tr class="package_row1">
              <td align="left">3</td>
              <td align="left">Combo</td>
              <td align="left">Description</td>
               <td align="left">40</td>
              <td align="left" class="last image"><img title="Active" src="<?php echo $this->cdnUri()?>/images/icons/active-1.png" /></td>
            </tr>
            <tr class="package_row1">
              <td align="left">4</td>
              <td align="left">Retail Production</td>
              <td align="left">Description</td>
               <td align="left">55</td>
              <td align="left" class="last image"><img title="Active" src="<?php echo $this->cdnUri()?>/images/icons/active-1.png" /></td>
            </tr>
          </table>
        </div>
      </div>
      <div class="result_box">Results: 1-20 of 50</div>
      <div class="paging">
        <ul>
          <li>
            <a href="#" class="arrow-first" title="First">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-first.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-prev" title="Previous">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-prev.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="active" title="Page 1">1</a>
          </li>
          <li>
            <a href="#" title="Page 2">2</a>
          </li>
          <li>
            <a href="#" title="Page 3">3</a>
          </li>
          <li>
            <a href="#" class="arrow-next" title="Next">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-next.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-last" title="Last">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-last.png" alt="">
            </a>
          </li>
        </ul>
      </div>
      
      <script type="text/javascript">
		
        // Script For Grid Starts //
		$(document).ready(function(){
			//row click
			$('tr.package_row1').click(function (event) {
								$('tr.package_row1').toggleClass('active', false);
								$(this).toggleClass('active', true);
								});
			// table Width
			var tblWidth=0;
			$('.grid_table tr:first').children().each(function(index) {
									tblWidth = tblWidth + parseInt($(this).attr('width'));
									});
			//$(".grid_table").css("width", tblWidth);
		});

		$('.grid_table tr').find('td:last').addClass('last')
		$('.grid_table tr').find('th:last').addClass('last')
		// Script For Grid Ends //



		// Script For Scroll Panel Starts //
		$(function(){
		//$('.scroll-pane').jScrollPane({showArrows: true});
		});
		// Script For Scroll Panel Ends //


		// Script For Tabs Panel Starts //
			$(function(){
				$('#tabs').tabs();
			});
		// Script For Tabs Panel Ends //
        
     </script>