 <?php 

 $this->headScript()->appendFile("/js/tree/_lib/jquery.cookie.js");
 $this->headScript()->appendFile("/js/tree/_lib/jquery.hotkeys.js");
 $this->headScript()->appendFile("/js/tree/jquery.jstree.js");
 $this->headLink()->appendStylesheet('/js/tree/themes/default/style.css'); 

 ?>

<script language="javascript">


$(function () {
	$("#privilege_tree").jstree({ 
                "core" : { "initially_open" : [ "noderoot_0", "noderoot_1", "noderoot_2"] },
		"plugins" : [ "themes", "html_data", "ui", "crrm", , "types" ,"hotkeys", "checkbox"],

                "types" : {
                     "max_depth" : -2,
                        "max_children" : -2,
                        // I want only 'root' nodes to be root nodes
                        // This will prevent moving or creating any other type as a root node
                        "valid_children" : [ "root" ],
                      "types" : {
				"root" : {
					"icon" : {"image" : "/js/tree/themes/default/_drive.png" },
					"valid_children" : [ "default" ],
					"max_depth" : 2,
					"hover_node" : false,
                                        'rename_node' :false,
                                        'select_node' :false
				},
                                "group" : {
                                        "icon" : {"image" : "/js/tree/themes/default/folder.png" },
					"valid_children" : [ "subgroup" ],
					"max_depth" : 2,
					"hover_node" : false					
				},
                                "subgroup" : {
					"icon" : {"image" : "/js/tree/themes/default/folder.png" },
					"valid_children" : [ "role" ],
					"max_depth" : 2,
					"hover_node" : false
				},
                                "role" : {
                                        "icon" : {"image" : "/js/tree/themes/default/file.png" },
					"max_depth" : 2,
					"hover_node" : false,
                                        "valid_children" : "none"
                                       
				},
                                "s-role" : {
                                        "icon" : {"image" : "/js/tree/themes/default/file.png" },
					"max_depth" : 2,
					"hover_node" : false,
                                        "valid_children" : "none"
                                       
				},
				"default" : {
					"icon" : {"image" : "/js/tree/themes/default/folder.png" },
					"valid_children" : [ "subgroup" ],
					"max_depth" : 2,
					"hover_node" : false
				}
			}
    }
                    
               
	})
        
        ;
        
        
        $("input[name='rdo']").change(function(){
            var rdoval=$("input[name='rdo']:checked").val();
            if(rdoval=="rdoGroup")
            {
                $("#cmbGroup").removeAttr('disabled');

                $("#cmbSubGroup").attr('disabled', 'disabled');
                $("#cmbRole").attr('disabled', 'disabled');
                $("#cmbUser").attr('disabled', 'disabled');
            }else if(rdoval=="rdoSubGroup")
            {
                $("#cmbGroup").attr('disabled', 'disabled');
                $("#cmbSubGroup").removeAttr('disabled');

                $("#cmbRole").attr('disabled', 'disabled');
                $("#cmbUser").attr('disabled', 'disabled');
            }
            else if(rdoval=="rdoRole")
            {
                $("#cmbGroup").attr('disabled', 'disabled');
                $("#cmbSubGroup").attr('disabled', 'disabled');
                $("#cmbRole").removeAttr('disabled');

                $("#cmbUser").attr('disabled', 'disabled');
            }
            else if(rdoval=="rdoUser")
            {
                $("#cmbGroup").attr('disabled', 'disabled');
                $("#cmbSubGroup").attr('disabled', 'disabled');
                $("#cmbRole").attr('disabled', 'disabled');
                $("#cmbUser").removeAttr('disabled');

            }
        });
});

</script>
<form>
    <div class="bone_panel">
        <table class="from_table" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td align="right" class="form_tab_lebel" valign="top">Action Name : </td>
                <td align="left" class="form_tab_input" valign="top"><input type="text" /></td>
                
            </tr>
            
           <tr>
                <td align="right" class="form_tab_lebel" valign="top">&nbsp; </td>
                
                <td align="left" class="form_tab_input" style="padding-top:10px;" valign="top"><input type="button" value="Add Action" class="yellow_button yellow_button_cow" /></td>
            </tr> 
            
        </table>
        <div class="sep_left">&nbsp;</div>
        <div class="cus_order">
            
            <table class="from_table" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="right" class="form_tab_lebel" valign="top"><div class="rework_tab_bx1">
            <input type="radio" name="rdo" id="rdo" checked="checked" value="rdoGroup">
            Group: </div></td>
    <td align="left" class="form_tab_input" valign="top"><select id="cmbGroup">
                <option value="">-- Select --</option>
                <?php for($i=1;$i<21;$i++):?>
                <option value="Group<?php echo $i;?>">Group<?php echo $i;?></option>
                <?php endfor;?>
            </select></td>
  </tr>
  
  <tr>
    <td align="right" class="form_tab_lebel" valign="top"><div class="rework_tab_bx1">
            <input type="radio" name="rdo" id="rdo" value="rdoSubGroup">
            Sub Group: </div></td>
    <td align="left" class="form_tab_input" valign="top"><select id="cmbSubGroup" disabled="disabled">
                <option value="">-- Select --</option>
                <?php for($i=1;$i<21;$i++):?>
                <option value="SubGroup<?php echo $i;?>">SubGroup<?php echo $i;?></option>
                <?php endfor;?>
            </select></td>
  </tr>
 
  
  <tr>
    <td align="right" class="form_tab_lebel" valign="top"><div class="rework_tab_bx1">
            <input type="radio" name="rdo" id="rdo" value="rdoRole">
            Role: </div></td>
    <td align="left" class="form_tab_input" valign="top"><select id="cmbRole" disabled="disabled">
                <option value="">-- Select --</option>
                <?php for($i=1;$i<21;$i++):?>
                <option value="Role<?php echo $i;?>">Role<?php echo $i;?></option>
                <?php endfor;?>
            </select></td>
  </tr>
 
   <tr>
    <td align="right" class="form_tab_lebel" valign="top"><div class="rework_tab_bx1">
            <input type="radio" name="rdo"  id="rdo" value="rdoUser">
            User: </div></td>
    <td align="left" class="form_tab_input" valign="top"> <select id="cmbUser" disabled="disabled">
                <option value="">-- Select --</option>
                <?php for($i=1;$i<21;$i++):?>
                <option value="User<?php echo $i;?>">User<?php echo $i;?></option>
                <?php endfor;?>
            </select></td>
  </tr>
  
  
  <tr>
    <td align="right" class="form_tab_input" style="padding-top:10px;" valign="top"><input type="button" class="yellow_button" id="addon" value="Get Permission"></td>
    <td align="left" class="form_tab_input" style="padding-top:10px;" valign="top"><input type="button" id="" class="yellow_button" value="Save Permission"></td>
  </tr>
  
</table>
          
        </div>
        <div class="pallet_order">
      
          
         <div class="form_field_tree">
            
                    <div id="privilege_tree" class="demo">
                        <ul>
                            <li id="noderoot_0" rel="root">
                                <a href="#" >All</a>
                                    <?php for($i=1;$i<21;$i++):?>
                                    <ul><li><a href="#" >Action - <?php echo $i?></a></li></ul>
                                    
                                    <?php endfor;?>
                            </li>
                        </ul>
                    </div>
              
              
          </div>
          
          
       
        </div>    
    
  
    </div>    
   
     
       
    
        
    
   
    



      </form>

