

<div id="dialog-modal" title="Change Password">
        <form name="addon_form">

           
        <div class="form_row">
            <div class="form_label">New Password: <span class="required">*</span></div>
            <div class="form_field">
                <input autocomplete="Off" type="password" >
            </div>

        </div>

        <div class="form_row">
            <div class="form_label">Retype Password: <span class="required">*</span></div>
            <div class="form_field">
           <input autocomplete="Off" type="password"   >
            </div>

        </div>

        </form>
</div>



<script type="text/javascript">
    $(function() {
            
            $("#dialog-modal").hide();

    $(".changepassword").click(function() {
            $("#dialog-modal").dialog({
                    height: 260,
                    width: 500,
                    modal: true,
                    resizable: false,
                    buttons: {
				'Ok': function() {
					$(this).dialog('close');
				},
				Cancel: function() {
					$(this).dialog('close');
				}
			}


            });
    });
    });
    
</script>



<form>
    
    <table class="from_table" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="right" class="form_tab_lebel" valign="top">Name:</td>
    <td align="left" class="form_tab_input" valign="top"><input type="text" value=""></td>
    <td align="left" class="form_tab_input" valign="top"><input type="button" class="search" value="Search"><img class="search_img" src="<?php echo $this->cdnUri()?>/images/search_img.png" alt=""></td>
  </tr>
</table>
    
       
      </form>
      <div class="result_box">Results: 1-20 of 50</div>
      <div class="paging">
        <ul>
          <li>
            <a href="#" class="arrow-first" title="First">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-first.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-prev" title="Previous">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-prev.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="active" title="Page 1">1</a>
          </li>
          <li>
            <a href="#" title="Page 2">2</a>
          </li>
          <li>
            <a href="#" title="Page 3">3</a>
          </li>
          <li>
            <a href="#" class="arrow-next" title="Next">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-next.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-last" title="Last">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-last.png" alt="">
            </a>
          </li>
        </ul>
      </div>
      <div class="gird_box">
        <div class="scroll-pane">
          <table style="margin: 0 0 15px 0" class="grid_table" border="0"  cellspacing="0" cellpadding="0">
            <tr>
              <th align="left" width="60">S. No</th>
              <th align="left" width="160">User Name</th>
              <th align="left" width="130">Group<img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
              <th align="left" width="130">Sub Group<img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
              <th align="left" width="180">Role<img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
              <th align="left" width="100">First Name</th>
              <th align="left" width="100">Last Name</th>
              <th align="left" width="150">Supervisor<img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
              <th align="left" width="120">Email</th>
	            <th align="left" width="200">Action</th>
            </tr>
            <?php for($i=1;$i<21;$i++):?>
            <tr class="package_row1">
              <td align="left"><?php echo $i?>.</td>
              <td align="left">NixNoodleNumbat</td>
              <td align="left">Management</td>
              <td align="left">Testing</td>
              <td align="left">Management</td>
              <td align="left">Mabel</td>
              <td align="left">Edwin</td>
              <td align="left">Arthur Edwin</td>
              <td align="left">test.test@test.com</td>
      	      <td class="image" align="left"><a href="#"><img title="Edit" alt="Edit"src="<?php echo $this->cdnUri()?>/images/icons/edit.png" /></a>  <a href="#"><img title="Delete" alt="Delete"src="<?php echo $this->cdnUri()?>/images/icons/del.png" /></a>
                <!-- <input type="button" value="Password" class="gray_button_dark changepassword"/> -->
              </td>
           
            </tr>
            <?php endfor;?>
          </table>
        </div>
      </div>
      <div class="result_box">Results: 1-20 of 50</div>
      <div class="paging">
        <ul>
          <li><a href="#" class="arrow-first" title="First"><img src="<?php echo $this->cdnUri()?>/images/arrow-first.png" alt=""></a></li>
          <li><a href="#" class="arrow-prev" title="Previous"><img src="<?php echo $this->cdnUri()?>/images/arrow-prev.png" alt=""></a></li>
          <li><a href="#" class="active" title="Page 1">1</a></li>
          <li><a href="#" title="Page 2">2</a></li>
          <li><a href="#" title="Page 3">3</a></li>
          <li><a href="#" class="arrow-next" title="Next"><img src="<?php echo $this->cdnUri()?>/images/arrow-next.png" alt=""></a></li>
          <li><a href="#" class="arrow-last" title="Last"><img src="<?php echo $this->cdnUri()?>/images/arrow-last.png" alt=""></a></li>
        </ul>
      </div>
      
      
      
      <script type="text/javascript">
		
		
        // Script For Grid Starts //
		$(document).ready(function(){
			//row click
			$('tr.package_row1').click(function (event) {
								$('tr.package_row1').toggleClass('active', false);
								$(this).toggleClass('active', true);
								});
			// table Width
			var tblWidth=0;
			$('.grid_table tr:first').children().each(function(index) {
									tblWidth = tblWidth + parseInt($(this).attr('width'));
									});
			$(".grid_table").css("width", tblWidth);
		});

		$('.grid_table tr').find('td:last').addClass('last')
		$('.grid_table tr').find('th:last').addClass('last')
		// Script For Grid Ends //



		// Script For Scroll Panel Starts //
		$(function(){
		$('.scroll-pane').jScrollPane({showArrows: true});
		});
		// Script For Scroll Panel Ends //


		// Script For Tabs Panel Starts //
			$(function(){
				$('#tabs').tabs();
			});
		// Script For Tabs Panel Ends //
        
     </script>