<form name="create_customer">
  <div class="form_row form_separate">
    <div class="form_label">
      Organization: <span class="required">*</span>
    </div>
    <div class="form_field">
      <select id="selectOrg">
        <option value="">--Add--</option>
        <option value="Org1">Org1</option>
        <option value="Org2">Org2</option>
      </select>
    </div>
  </div>
  
  <div class="form_row ">
    <div class="form_row">
      <div class="form_label" id="lbl" >
        <h2> Add Organization</h2>
      </div>
    </div>
  </div>
  <div class="form_row">
      <div class="form_label">
        Organization Name: <span class="required">*</span>
      </div>
      <div class="form_field">
        <input type="text" id="txtOrg" name="txtOrg">
        </div>
    </div>
  <div class="form_row">
    <div class="form_label">
      First Name: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="" id="txtfirstname">
        </div>
    <div class="form_label">
      Last Name: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="" id="txtlastname">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      Address1: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" id="address" value=" ">
    </div>
    <div class="form_label">
      Address2:
    </div>
    <div class="form_field">
      <input type="text" value="">
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      City: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" id="city" >
        </div>
    <div class="form_label">
      State: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" id="state" >
        </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      Zip: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" id="zip" >
        </div>
  </div>
  <div class="form_row">
      <div class="form_label">
        Phone: <span class="required">*</span>
      </div>
      <div class="form_field">
        <input type="text" id="phone" >
</div>
      <div class="form_label">
        Fax: <span class="required">*</span>
      </div>
      <div class="form_field">
        <input type="text" id="fax" >
        </div>
    </div>
  <div class="form_row">
    <div class="form_label">
      Email: <span class="required">*</span>
    </div>
    <div class="form_field">
      <input type="text" value="" id="email">
        </div>

  </div>
    
    
    
    
    
    
  <div class="form_row">
      <div class="form_label">&nbsp;</div>
      <div class="form_field">
            <div class="rework_tab_bx1">
                <input type="checkbox" value="" name="">
                Default 
            </div>    
        </div>
    </div>
    
  <div class="form_row">
      <div class="form_label">&nbsp;</div>
      <div class="form_field">
        <input id="btnSubmit" type="button" value="Submit">
        </div>
    </div>
</form>

<script language="javascript">
$("#selectOrg").change(function (){
    if(this.value=="")
    {
        $("#btnSubmit").val("Submit");
        $("#lbl").html("<h2>Add Organization</h2>");
        $("#txtOrg").val(this.value);
        $("#txtfirstname").val("");
        $("#txtlastname").val("");
        $("#fax").val("");
        $("#phone").val("");
        $("#address").val("");
        $("#city").val("");
        $("#state").val("");
        $("#zip").val("");
        $("#email").val("");
  }
  else
  {

  $("#txtOrg").val(this.value);
  $("#txtfirstname").val("FirstName");
  $("#txtlastname").val("LastName");
  $("#fax").val("123456");
  $("#phone").val("123456123");
  $("#address").val("test test test test");
  $("#city").val("Lko");
  $("#state").val("NJ");
  $("#zip").val("213456");
  $("#email").val("test@example.com");
  $("#lbl").html("<h2>Update Organization</h2>");
        $("#btnSubmit").val("Update");
    }
});    
</script>