<form>

  <table class="from_table" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td align="right" class="form_tab_lebel" valign="top">Menu ID:</td>
      <td align="left" class="form_tab_input" valign="top">
        <input type="text" value="">
      </td>
      <td align="right"  class="form_tab_lebel" valign="top">Menu Title:</td>
      <td align="left" class="form_tab_input" valign="top">
        <input type="text" value="">
      </td>
      <td align="right" class="form_tab_lebel" valign="top">Status: </td>
      <td align="left" class="form_tab_input" valign="top">
        <input type="text" value="">
      </td>

    </tr>
    <tr>
      <td align="right" class="form_tab_lebel" valign="top"></td>
      <td align="left" class="form_tab_input search_button" valign="top">
        <input class="search" value="Search" type="button">
          <img class="search_img" src="<?php echo $this->cdnUri()?>/images/search_img.png" alt="">
      </td>
      <td align="right"  class="form_tab_lebel" valign="top"></td>
      <td align="left" class="form_tab_input" valign="top"></td>
      <td align="right"  class="form_tab_lebel" valign="top"></td>
      <td align="left" class="form_tab_input" valign="top"></td>

    </tr>
  </table>
  
  

      </form>
      <div class="result_box">Results: 1-20 of 50</div>
      <div class="paging">
        <ul>
          <li>
            <a href="#" class="arrow-first" title="First">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-first.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-prev" title="Previous">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-prev.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="active" title="Page 1">1</a>
          </li>
          <li>
            <a href="#" title="Page 2">2</a>
          </li>
          <li>
            <a href="#" title="Page 3">3</a>
          </li>
          <li>
            <a href="#" class="arrow-next" title="Next">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-next.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-last" title="Last">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-last.png" alt="">
            </a>
          </li>
        </ul>
      </div>
      <div class="gird_box">
        <div class="scroll-pane">
          <table class="grid_table" border="0"  cellspacing="0" cellpadding="0" width="100%">
            <tr>
              <th align="left" width="10%">S. No</th>
              <th align="left" width="10%">Menu ID</th>
	      <th align="left" width="20%">Menu Title</th>
              <th align="left" width="15%">Menu Path<img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
              <th align="left" width="15%">Parent ID<img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
              <th align="left" width="15%">Is Active<img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
              <th align="left" width="15%">Is Child<img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt="">
            </th>
			  
            </tr>
           <?php for($i=1;$i<21;$i++){?>
            <tr class="package_row1">
              <td align="left"><?php echo $i; ?></td>
              <td align="left">Nixt<?php echo $i; ?></td>
              <td align="left">Management<?php echo $i; ?></td>
              <td align="left">Testing/test/<?php echo $i; ?></td>
              <td align="left">Parent <?php echo $i; ?></td>
              <td align="left" class="image"><img title="Active" src="<?php echo $this->cdnUri()?>/images/icons/active-1.png" /></td>
              <td align="left" class="image"><img title="Yes" src="<?php echo $this->cdnUri()?>/images/icons/active-1.png" /></td>
			  
            </tr>
	<?php } ?>	
		
          </table>
        </div>
      </div>
      <div class="result_box">Results: 1-20 of 50</div>
      <div class="paging">
        <ul>
          <li>
            <a href="#" class="arrow-first" title="First">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-first.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-prev" title="Previous">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-prev.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="active" title="Page 1">1</a>
          </li>
          <li>
            <a href="#" title="Page 2">2</a>
          </li>
          <li>
            <a href="#" title="Page 3">3</a>
          </li>
          <li>
            <a href="#" class="arrow-next" title="Next">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-next.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-last" title="Last">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-last.png" alt="">
            </a>
          </li>
        </ul>
      </div>
      
      <script type="text/javascript">
		
		
        // Script For Grid Starts //
		$(document).ready(function(){
			//row click
			$('tr.package_row1').click(function (event) {
								$('tr.package_row1').toggleClass('active', false);
								$(this).toggleClass('active', true);
								});
			// table Width
			var tblWidth=0;
			$('.grid_table tr:first').children().each(function(index) {
									tblWidth = tblWidth + parseInt($(this).attr('width'));
									});
			//$(".grid_table").css("width", tblWidth);
		});

		$('.grid_table tr').find('td:last').addClass('last')
		$('.grid_table tr').find('th:last').addClass('last')
		// Script For Grid Ends //



		// Script For Scroll Panel Starts //
		$(function(){
		//$('.scroll-pane').jScrollPane({showArrows: true});
		});
		// Script For Scroll Panel Ends //


		// Script For Tabs Panel Starts //
			$(function(){
				$('#tabs').tabs();
			});
		// Script For Tabs Panel Ends //
        
     </script>