<form name="create_menu">
        <div class="form_row">
          <div class="form_label">Title:<span class="required">*</span></div>
          <div class="form_field">
            <input type="text" value="">
          </div>
          <div class="form_label">
            Parent Menu: <span class="required">*</span>
          </div>
          <div class="form_field">
            <select>
              <option value="-- Select --">-- Select --</option>
              <option value="-- Select --">Buying</option>
              <option value="-- Select --">Production</option>
              <option value="-- Select --">Accounts</option>
              <option value="-- Select --">Inventory</option>
            </select>
          </div> 
          
          
        </div>
        
        
        <!-- <div class="form_row">
          <div class="form_label">Gender: <span class="required">*</span></div>
          <div class="form_field">
            <select>
              <option value="-- Select --">-- Select --</option>
            </select>
          </div>
        </div> -->
		<div class="form_row">
          <div class="form_label">Path: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_address" onkeyup="copy_shipping_to_billing(this);">
          </div>
      <div class="form_label">
        Tooltip: <span class="required">*</span>
      </div>
      <div class="form_field">
        <input type="text" name="shipping_f_name" onkeyup="copy_shipping_to_billing(this);">
          </div>
          
        </div>

		

        <div class="form_row">
          <div class="form_label">Is Active: <span class="required">*</span></div>
          
            <div class="form_field_same">
              <table  border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td>
                    <input name="is_active" type="radio" value="">
                  </td>
                  <td width="50">Yes</td>
                  <td>
                    <input name="is_active" type="radio" value="">
                  </td>
                  <td>No</td>
                </tr>


              </table>
            </div>
        
          </div>
          
     

		<div class="form_row">
          <div class="form_label">Is Child: <span class="required">*</span></div>
          
            <div class="form_field_same">
              <table  border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td><input name="is_child" type="radio" value=""></td>
                  <td width="50">Yes</td>
                    
                  <td>
                    <input name="is_child" type="radio" value="">
                  </td>
                  <td>
                    No
                  </td>
                </tr>
                
                
              </table>
            </div>
        
          </div>
          
       

		
        <div class="form_row">
          <div class="form_label">&nbsp;</div>
          <div class="form_field">
            <input type="button" value="Submit">
          </div>
        </div>
      </form>