<form>
<table class="from_table" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="right" class="form_tab_lebel" valign="top"><?php echo $this->puts("Order ID:")?></td>
    <td align="left" class="form_tab_input" valign="top"><input type="text" value=""></td>
    <td align="right"  class="form_tab_lebel" valign="top"><?php echo $this->puts("Customer ID:")?></td>
    <td align="left" class="form_tab_input" valign="top"><input type="text" value=""></td>
    
  </tr>

  <tr>
    <td align="right" class="form_tab_lebel" valign="top"><?php echo $this->puts("From:")?> </td>
    <td align="left" class="form_tab_input" valign="top"><div class="bone_date_bx2">
                <input type="text" id="datepicker">
              </div>
              </td>
    <td align="right"  class="form_tab_lebel" valign="top"><?php echo $this->puts("To:")?> </td>
    <td align="left" class="form_tab_input" valign="top"><div class="bone_date_bx2">
                <input type="text" id="Text1">
              </div></td>
    
  </tr>
  
  <tr>
    <td align="right" class="form_tab_lebel" valign="top">&nbsp;</td>
    <td align="left" class="form_tab_input search_button" valign="top"><input type="button" class="search" value="<?php echo $this->puts("Search")?>">
            <img class="search_img" src="<?php echo $this->cdnUri()?>/images/search_img.png" alt=""></td>
    <td align="right"  class="form_tab_lebel" valign="top">&nbsp;</td>
    <td align="left" class="form_tab_input" valign="top">&nbsp;</td>

  </tr>
  
</table>
    <script>
        $(function () {
            $("#datepicker,#Text1").datepicker({
                showOn: "button",
                buttonImage: "<?php echo $this->cdnUri()?>/images/calendar_icon.png",
                buttonImageOnly: true
            });
        });
    </script> 
 </form>
      <div class="result_box">Results: 1-20 of 50</div>
      <div class="paging">
        <ul>
          <li>
            <a href="#" class="arrow-first" title="First">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-first.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-prev" title="Previous">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-prev.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="active" title="Page 1">1</a>
          </li>
          <li>
            <a href="#" title="Page 2">2</a>
          </li>
          <li>
            <a href="#" title="Page 3">3</a>
          </li>
          <li>
            <a href="#" class="arrow-next" title="Next">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-next.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-last" title="Last">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-last.png" alt="">
            </a>
          </li>
        </ul>
      </div>
      <div class="gird_box">
        <div class="scroll-pane">
          <table class="grid_table" style="margin:0 0 15px 0;" border="0"  cellspacing="0" cellpadding="0">
            <tr>
              <th align="left" width="80"><?php echo $this->puts("Order ID")?></th>
              <th align="left" width="180"><?php echo $this->puts("Product Name")?></th>
               <th align="left" width="140"><?php echo $this->puts("P.O Number")?></th>
              <th align="left" width="120"><?php echo $this->puts("Order Date")?></th>
              <th align="left" width="100"><?php echo $this->puts("Unit")?></th>
              <th align="left" width="120"><?php echo $this->puts("Avg Case Wt.")?></th>
              <th align="left" width="100"><?php echo $this->puts("Price/lb ($)")?></th>
              <th align="left" width="100"><?php echo $this->puts("Case Shipped")?></th>
              <th align="left" width="100"><?php echo $this->puts("Lbs to Order")?> </th>
              <th align="left" width="100"><?php echo $this->puts("Action")?> </th>
              
            </tr>
            <?php for($i=1;$i<21;$i++){?>
            <tr class="package_row1">
              <td align="left">00<?php echo $i; ?></td>
              <td align="left">Ribeye 8-10</td>
               <td align="left">Verbal 03/<?php echo $i; ?></td>
               <td align="left">04/01/2012</td>
              <td align="left">1</td>
              <td align="left">63.00</td>
              <td align="left">$10.00</td>
              <td align="left">0.00</td>
              <td align="left"> 0.00</td>
            <td class="image" align="left"><a href=" " style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/edit.png" border="0" title="Edit"/></a>  <a href=" "  style="color:#555d6a"><img alt="" src="<?php echo $this->cdnUri()?>/images/icons/del.png" border="0" title="Delete"/></a></td>
             
            </tr>
            <?php } ?>
                        
          </table>
        </div>
      </div>
      <div class="result_box">Results: 1-20 of 50</div>
      <div class="paging">
        <ul>
          <li>
            <a href="#" class="arrow-first" title="First">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-first.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-prev" title="Previous">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-prev.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="active" title="Page 1">1</a>
          </li>
          <li>
            <a href="#" title="Page 2">2</a>
          </li>
          <li>
            <a href="#" title="Page 3">3</a>
          </li>
          <li>
            <a href="#" class="arrow-next" title="Next">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-next.png" alt="">
            </a>
          </li>
          <li>
            <a href="#" class="arrow-last" title="Last">
              <img src="<?php echo $this->cdnUri()?>/images/arrow-last.png" alt="">
            </a>
          </li>
        </ul>
      </div>
      
      <script type="text/javascript">
		
		
        // Script For Grid Starts //
		$(document).ready(function(){
			//row click
			$('tr.package_row1').click(function (event) {
								$('tr.package_row1').toggleClass('active', false);
								$(this).toggleClass('active', true);
								});
			// table Width
			var tblWidth=0;
			$('.grid_table tr:first').children().each(function(index) {
									tblWidth = tblWidth + parseInt($(this).attr('width'));
									});
			$(".grid_table").css("width", tblWidth);
		});

		$('.grid_table tr').find('td:last').addClass('last')
		$('.grid_table tr').find('th:last').addClass('last')
		// Script For Grid Ends //



		// Script For Scroll Panel Starts //
		$(function(){
		$('.scroll-pane').jScrollPane({showArrows: true});
		});
		// Script For Scroll Panel Ends //


		// Script For Tabs Panel Starts //
			$(function(){
				$('#tabs').tabs();
			});
		// Script For Tabs Panel Ends //
        
     </script>