    
      <div class="bone_panel">
        <div class="cus_order">
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="left" valign="top"><div class="bone_left_head">
                  <h2><?php echo $this->puts("Customer Order")?></h2>
                </div></td>
            </tr>
            <tr>
              <td align="left" valign="top"><div class="bone_date_des">
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td align="left" valign="top" width="30%"><div class="bone_date_cus">
                          <div class="bone_date_bx1" style="padding:7px 0 0 0;"><?php echo $this->puts("Date:")?> </div>
                          <div class="bone_date_bx2">
                            <input type="text" id="datepicker">
                          </div>
                          <script>
							$(function() {
								$( "#datepicker" ).datepicker({
									showOn: "button",
									buttonImage: "<?php echo $this->cdnUri()?>/images/calendar_icon.png",
									buttonImageOnly: true
								});
							});
							</script>
                        </div></td>
                      <td align="left" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td align="right" class="bone_date_des_order_text" style="padding:0 5px 7px 0;"><?php echo $this->puts("Customer:")?></td>
                            <td class="bone_date_des_order_in" align="left"><select name="">
                                <option value="1">-- Select --</option>
                                <option>Mark Vincy</option>
                                <option>Nathan Lee</option>
                                <option>Stephan Ronald</option>
                              </select></td>
                          </tr>
                          <tr>
                            <td align="right" class="bone_date_des_order_text"><?php echo $this->puts("Order:")?></td>
                            <td class="bone_date_des_order_in" align="left"><select name="">
                                <option value="1">-- Select --</option>
                                <option>001</option>
                                <option>002</option>
                                <option>003</option>
                              </select></td>
                          </tr>
                          <tr>
                            <td align="right" class="bone_date_des_order_text" ><?php echo $this->puts("Enter Order ID:")?></td>
                            <td align="left"><input name="" type="text"></td>
                          </tr>
                        </table></td>
                    </tr>
                  </table>
                </div></td>
            </tr>
            <tr>
              <td style="padding: 0 0 20px 0;"><table border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td><input type="button" class="gray_button_dark" value="<?php echo $this->puts("Smith Retail")?>"></td>
                    <td><input type="button" value="Smith Grind" class="gray_button_dark"></td>
                    <td><input type="button" value="Smith North" class="gray_button_dark"></td>
                  </tr>
                </table></td>
            </tr>
          </table>
          
          
          <div class="gird_box">
                  <div class="scroll_pane_bone">
                    <table class="grid_table" border="0"  cellspacing="0" cellpadding="0">
                      <tr>
                        <th align="left" width="80"><?php echo $this->puts("Product ID")?></th>
                        <th align="left" width="160"><?php echo $this->puts("Product Name")?></th>
                        <th align="left" width="120"><?php echo $this->puts("Total Weight")?><img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
                        <th align="left" width="100"><?php echo $this->puts("Acc. Weight")?></th>
                        <th align="left" width="100"><?php echo $this->puts("Ordered")?></th>
                        <th align="left" width="100"><?php echo $this->puts("Completed")?></th>
                      </tr>
                       <?php for($i=1;$i<21;$i++){?>
                      <tr class="package_row1">
                        <td align="left"><?php echo $i; ?></td>
                        <td align="left">Ground EyeRound</td>
                        <td align="left">203</td>
                        <td align="left">203</td>
                        <td align="left">0</td>
                        <td align="left" class="image">0</td>
                      </tr>
                      <?php } ?>
                      
                    </table>
                  </div>
                </div>
          
          
          
          <script type="text/javascript">
		
		
        // Script For Grid Starts //
		$(document).ready(function(){
			//row click
			$('tr.package_row1').click(function (event) {
								$('tr.package_row1').toggleClass('active', false);
								$(this).toggleClass('active', true);
								});
			// table Width
			var tblWidth=0;
			$('.grid_table tr:first').children().each(function(index) {
									tblWidth = tblWidth + parseInt($(this).attr('width'));
									});
			$(".grid_table").css("width", tblWidth);
		});

		$('.grid_table tr').find('td:last').addClass('last')
		$('.grid_table tr').find('th:last').addClass('last')
		
		// Script For Grid Ends //



		// Script For Scroll Panel Starts //
		$(function(){
		$('.scroll_pane_bone').jScrollPane({showArrows: true});
		});
		// Script For Scroll Panel Ends //
     </script>
          
          
        </div>
        <div class="pallet_order">
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td align="left" valign="top"><div class="bone_left_head">
                  <h2><?php echo $this->puts("Pallet Order")?></h2>
                </div></td>
            </tr>
            <tr>
              <td align="left" valign="top"><div class="bone_date_des_order">
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td width="50%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td valign="top" class="pallet_ord" width="30" align="left" style="padding-top:8px;"><?php echo $this->puts("Pallet:")?> </td>
                            <td class="pallet_ord" align="left"><select name="" size="4" multiple style="width:91px;">
                                <option value="1">Pallet 1</option>
                                <option value="2">Pallet 2</option>
                                <option value="3">Pallet 3</option>
                                <option value="4">Pallet 4</option>
                                <option value="5">Pallet 5</option>
                              </select></td>
                          </tr>
                          <tr>
                            <td>&nbsp;</td>
                            <td><input name="" type="button" class="add_pallet" value="" src="<?php echo $this->cdnUri()?>/images/add_pal_img.gif"></td>
                          </tr>
                        </table></td>
                      <td width="50%" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td valign="top" class="pallet_ord" align="right"><?php echo $this->puts("Barcode:")?> </td>
                            <td><input name="" type="text"></td>
                          </tr>
                        </table></td>
                    </tr>
                  </table>
                </div></td>
            </tr>
            <tr>
              <td valign="top" class="order_pad"><table border="0" width="100%" cellspacing="0" cellpadding="0">
                  <tr>
                    <td class="print_re" valign="top"><table border="0" cellspacing="0" cellpadding="0">
                        <tr>
                          <td><a href="#" title="Print"><img src="<?php echo $this->cdnUri()?>/images/print_icon.png" alt="" border="0" align="absmiddle"></a></td>
                          <td><a href="#" title="Print"><?php echo $this->puts("Print")?></a></td>
                        </tr>
                      </table></td>
                    <td align="right" valign="top" style="padding: 10px 0 0 0;"><input name="" class="yellow_button" type="button" value="<?php echo $this->puts("Order Complete")?>"></td>
                  </tr>
                </table></td>
            </tr>
            
          </table>
          
          <div class="gird_box">
                  <div class="scroll_pane_bone scroll_pane_bone1">
                    <table class="grid_table grid_table2" border="0"  width="100%" cellspacing="0" cellpadding="0">
                      <tr>
                        <th align="left" width="60"><?php echo $this->puts("Barcode")?></th>
                        <th align="left" width="60"><?php echo $this->puts("Weight")?></th>
                        <th align="left" width="60"><?php echo $this->puts("Product ID")?><img src="<?php echo $this->cdnUri()?>/images/arrow.gif" align="right" alt=""></th>
                        <th align="left" width="90"><?php echo $this->puts("Pallet")?></th>
                        <th align="left" width="120"><?php echo $this->puts("Action")?></th>
                      </tr>
                      <tr class="package_row1">
                        <td align="left">102312345<?php echo $i; ?></td>
                        <td align="left">350</td>
                        <td align="left">1</td>
                        <td align="left" class="image"><input type="text" class="" value="Pallet1" /></td>
                        <td class="last image" align="left">
                        <a href="javascript:void(0);"><img alt="Edit" src="<?php echo $this->cdnUri()?>/images/icons/edit.png" border="0" title="Edit"/></a>
			<a href='javascript:void(0); '  style='color:#555d6a'><img alt='' src='<?php echo $this->cdnUri()?>/images/icons/accept.png' border='0' title='Accept'/></a>
                        <a href="javascript:void(0);" onclick="if(confirm('Are you sure to delete this data?')){ alert('OK, deleted') } else { alert ('Not deleted')}"><img src="<?php echo $this->cdnUri();?>/images/icons/del.png" title="Delete" /></a>
                
                        </td>
                      </tr>
                       <?php for($i=2;$i<21;$i++){?> 
                      <tr class="package_row1">
                        <td align="left">102312345<?php echo $i; ?></td>
                        <td align="left">350</td>
                        <td align="left"><?php echo $i; ?></td>
                        <td align="left">Pallet<?php echo $i; ?></td>
                        <td class="last image" align="left">
                        <a href="javascript:void(0);"><img alt="Edit" src="<?php echo $this->cdnUri()?>/images/icons/edit.png" border="0" title="Edit"/></a>
			<a href='javascript:void(0); '  style='color:#555d6a'><img alt='' src='<?php echo $this->cdnUri()?>/images/icons/accept.png' border='0' title='Accept'/></a>
                        <a href="javascript:void(0);" onclick="if(confirm('Are you sure to delete this data?')){ alert('OK, deleted') } else { alert ('Not deleted')}"><img src="<?php echo $this->cdnUri();?>/images/icons/del.png" title="Delete" /></a>
                
                        </td>
                      </tr>
                      <?php } ?>
                    </table>
                  </div>
                </div>
          
          
          
          <script type="text/javascript">
		
		
        // Script For Grid Starts //
		$(document).ready(function(){
			//row click
			$('tr.package_row1').click(function (event) {
								$('tr.package_row1').toggleClass('active', false);
								$(this).toggleClass('active', true);
								});
			// table Width
			var tblWidth=0;
			$('.grid_table2 tr:first').children().each(function(index) {
									tblWidth = tblWidth + parseInt($(this).attr('width'));
									});
			//$(".grid_table2").css("width", tblWidth);
		});

		$('.grid_table tr').find('td:last').addClass('last')
		$('.grid_table tr').find('th:last').addClass('last')
		
		// Script For Grid Ends //



		// Script For Scroll Panel Starts //
		$(function(){
		$('.scroll_pane_bone1').jScrollPane({showArrows: true});
		});
		// Script For Scroll Panel Ends //
     </script>
       <!--    <table border="0" width="100%" cellspacing="0" cellpadding="0">
                  <tr>
                    <td align="right" class="order_com"><input name="" type="button" value="Order Complete"></td>
                  </tr>
                </table>  -->
        </div>
      </div>