<form name="create_customer">
        
		<div class="form_row"><div class="form_label"> <h2> Add On </h2></div></div>
        <div class="form_row">
          <div class="form_label">Des. of Add-on: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_f_name" onkeyup="copy_shipping_to_billing(this);">
          </div>
          
        </div>
      
        <div class="form_row">
          <div class="form_label">Quantity: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_address" onkeyup="copy_shipping_to_billing(this);">
          </div>
          
        </div>

		<div class="form_row">
          <div class="form_label">Price: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_state" onkeyup="copy_shipping_to_billing(this);">
          </div>          
        </div>
		
        <div class="form_row">
          <div class="form_label">&nbsp;</div>
          <div class="form_field">
            <input type="button" value="Submit">
          </div>
        </div>
      </form>