<?php echo  $this->flashMessages()?>
<form method="post">
  <div class="form_row">
    <div class="form_label">
      <?php echo $this->puts($this->form->userId->getLabel())?>  <span class="required">*</span>
    </div>
   <div class="form_field">
      <?php echo $this->form->userId?>
    </div>
  </div>
  <div class="form_row">
    <div class="form_label">
      <?php echo $this->puts($this->form->password->getLabel());?> <span class="required">*</span>
    </div>
    <div class="form_field">
      <?php echo $this->form->password;?>
        </div>
    <div class="form_label">
      <?php echo $this->puts($this->form->confirmPassword->getLabel());?> <span class="required">*</span>
    </div>
    <div class="form_field">
      <?php echo $this->form->confirmPassword;?>
        </div>
  </div>
  
  <div class="form_row">
    <div class="form_label">&nbsp;</div>
    <div class="form_field">
      <?php echo $this->form->submit;?>
        </div>
  </div>
</form>
