<?php //echo $this->totalItemCount; ?>

<form method="post" action="<?php echo $this->seoUrl("/admin/supplier/index")?>">
    
 <table class="from_table" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="right" class="form_tab_lebel" valign="top"><?php echo $this->puts('Organization Name');?>:</td>
    <td align="left" class="form_tab_input" valign="top"><input type="text" value="" name="orgName"></td>
    
    <td align="left" class="form_tab_input" valign="top"><input class="search" value="Search" type="submit" name="search"><img class="search_img" src="<?php echo $this->cdnUri()?>/images/search_img.png" alt=""></td>
  </tr>
  
</table>
    
       
</form>

<?php if (count($this->paginator)): ?>


        <?php
        $sno=0;
        $page=$this->paginator->getCurrentPageNumber();
        $items_per_page=$this->paginator->getItemCountPerPage(); 
        if($page>1)
        {
                $sno=$items_per_page*$page - $items_per_page ; 	
        }
        ?>
        <?php 
        if($this->paginator->count()>1)
        {    
           echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));
        }       
        ?>
<div> <?php echo $this->flashMessages()?> </div>


    <div class="gird_box">
        <div class="scroll-pane">
          <table style="margin: 0 0 15px 0" class="grid_table" border="0"  cellspacing="0" cellpadding="0">
            <tr>
              <th align="left" width="35"><?php echo $this->puts('S.No.');?></th>
              <th align="left" width="180"><?php echo $this->puts('Organization Name');?></th>
              <th align="left" width="130"><?php echo $this->puts('First Name');?></th>
              <th align="left" width="130"><?php echo $this->puts('Last Name');?></th>
              <th align="left" width="180"><?php echo $this->puts('Address');?></th>
              <th align="left" width="110"><?php echo $this->puts('City');?> <?php echo $this->sort("city", $this->sortOptions);?></th>
              <th align="left" width="110"><?php echo $this->puts('State');?> <?php echo $this->sort("state", $this->sortOptions);?></th>
              <th align="left" width="100"><?php echo $this->puts('Zip');?> <?php echo $this->sort("zip", $this->sortOptions);?></th>
              <th align="left" width="100"><?php echo $this->puts('Phone');?></th>
              <th align="left" width="100"><?php echo $this->puts('Fax');?></th>
              <th align="left" width="150"><?php echo $this->puts('Email');?></th>
              <th align="left" width="120"><?php echo $this->puts('Action');?></th>
            </tr>
            
            <?php 
        foreach ($this->paginator as $item): ?>
        <?php $sno++?>
          
            <tr class="package_row1">
              <td align="left"><?php echo $sno?>.</td>
              <td align="left"><?php echo $item->org_name;?></td>
              <td align="left"><?php echo $item->first_name;?></td>
              <td align="left"><?php echo $item->last_name;?></td>
              <td align="left"><?php echo $item->address1;?></td>
              <td align="left"><?php echo $item->city;?></td>
              <td align="left"><?php echo $item->state;?></td>
              <td align="left"><?php echo $item->zip;?></td>
              <td align="left"><?php echo $item->phone;?></td>
              <td align="left"><?php echo $item->fax;?></td>
              <td align="left"><?php echo $item->email;?></td>
              <td class="image" align="left">
                  
                  
                  <a href="<?php echo $this->seoUrl("/admin/supplier/edit-supplier/id/".$item->id)?>"><img title="Edit" alt="Edit"src="<?php echo $this->cdnUri()?>/images/icons/edit.png" /></a>  
                  
                 <?php if( $item->status=="1") {
                    $title="Click here to make user inactive!";
                    $image="/images/icons/accept.png";
                }else{
                    $image="/images/icons/del.png";
                    $title="Click here to make user active!";
                }?> 
                  
              <a href="<?php echo $this->seoUrl("/admin/supplier/change-user-status/guid/".$item->row_guid."/id/".$item->id)?>"><img title="<?php echo $title?>" alt="<?php echo $title?>" src="<?php echo $image?>" /></a> 
              </td>
           
            </tr>
            <?php endforeach; ?>
          </table>
        </div>
      </div>
        <?php 
        if($this->paginator->count()>1)
        {    
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));
        }       
        ?>

<?php endif; ?>










<script type="text/javascript">
		
		
        // Script For Grid Starts //
		$(document).ready(function(){
			//row click
			$('tr.package_row1').click(function (event) {
								$('tr.package_row1').toggleClass('active', false);
								$(this).toggleClass('active', true);
								});
			// table Width
			var tblWidth=0;
			$('.grid_table tr:first').children().each(function(index) {
									tblWidth = tblWidth + parseInt($(this).attr('width'));
									});
			$(".grid_table").css("width", tblWidth);
		});

		$('.grid_table tr').find('td:last').addClass('last')
		$('.grid_table tr').find('th:last').addClass('last')
		// Script For Grid Ends //



		// Script For Scroll Panel Starts //
		$(function(){
		$('.scroll-pane').jScrollPane({showArrows: true});
		});
		// Script For Scroll Panel Ends //


		// Script For Tabs Panel Starts //
			$(function(){
				$('#tabs').tabs();
			});
		// Script For Tabs Panel Ends //
        
     </script>
