<script type="text/javascript">
    $(function() {
    $("#dialog-modal").hide();
    $("#addon").click(function() {
    $("#dialog-modal-image").dialog({
                    width: 700,
                    height: 600,
                    modal: true,
                    resizable: false,
                    
                    buttons: {
				'Close': function() {
					$(this).dialog('close');
				}/*,
				'Cancel': function() {
					$(this).dialog('close');
                                       // $("#menuIcon").val('');
				}*/
			}
            });
            
    });
    });
function fillIcon(icon)
{
    $("#menuIcon").val(icon);
    $("#dialog-modal-image").dialog('close');
}  
</script>

<style>
  .ic:hover,.ic,#addon{
        cursor: pointer;
    }
    .ic{
        border:1px solid #CBCED7;
        padding: 4px;
    }
    .ic:hover{
        border:1px solid #FDDB5D;
    }
    .image-box{
        float:left;
        margin:5px
    }
</style>


<div id="dialog-modal-image" title="Select Menu Icon" style="display:none;">
        <div name="image-continer">
                    <?php
                    $dir=$this->icons;
                    if (count($dir)>0)
                    {
                        $imgPath=$this->cdnUri()."/media/menu-icons/";
                        $size='width="65" height="60"';
                        $size='';
                        foreach($dir as $img) 
                        {
                            if($img!="Thumbs.db"){
                            ?>
                                <div class="image-box"><img class="ic ui-icon-closethick" alt="<?php echo $img; ?>"  title ="<?php echo $img; ?>" src="<?php echo $imgPath.$img; ?>" <?php echo $size; ?> onclick="fillIcon('<?php echo $img; ?>')" /></div>
                            <?php
                            }
                        }
                    }
                    else
                    {
                        ?>
                       Icons not found
                        <?php
                    }
                    ?>
        </div>
</div>
<?php echo  $this->flashMessages()?>

<form method="post">
    <div class="form_row">
        <div class="form_label"><?php echo $this->puts($this->form->title->getLabel());?><span class="required">*</span></div>
        <div class="form_field"><?php echo $this->form->title?></div>
        <div class="form_label"><?php echo $this->puts($this->form->parentMenuId->getLabel());?></div>
        <div class="form_field"><?php echo $this->form->parentMenuId?></div> 
    </div>


    <div class="form_row">
        <div class="form_label"><?php echo $this->puts($this->form->path->getLabel());?><span class="required">*</span></div>
        <div class="form_field"><?php echo $this->form->path?></div>
        <div class="form_label"><?php echo $this->puts($this->form->toolTip->getLabel());?></div>
        <div class="form_field"><?php echo $this->form->toolTip?></div>
    </div>

    <div class="form_row">
        <div class="form_label"><?php echo $this->puts($this->form->isActive->getLabel());?></div>
        <div class="form_field_same"><?php echo $this->form->isActive?></div>
        <div class="form_label" style="margin-left:21px;"><?php echo $this->puts($this->form->menuIcon->getLabel());?></div>
        <div class="form_field"><?php echo $this->form->menuIcon;?> <img src="<?php echo $this->cdnUri();?>/images/choose-icons.jpg" id="addon" title="Select Menu Icons" border="0" align="absmiddle" /></div>

    </div>
    <div class="form_row">
        <div class="form_label"><?php echo $this->puts($this->form->isChild->getLabel());?></div>
        <div class="form_field_same"><?php echo $this->form->isChild?></div>
        <div class="form_label"><?php echo $this->puts($this->form->isAction->getLabel());?></div>
        <div class="form_field_same"><?php echo $this->form->isAction?></div>
    </div>




    <div class="form_row">
        <div class="form_label">&nbsp;</div>
        <div class="form_field"><?php echo $this->form->submit?></div>
    </div>
</form>
