
<form method='post' action="<?php echo $this->seoUrl("/security/menu/index")?>" >

  <table class="from_table" border="0" cellspacing="0" cellpadding="0">
    <tr>
      
      <td align="right"  class="form_tab_lebel" valign="top"><?php echo $this->puts('Menu Title');?>:</td>
      <td align="left" class="form_tab_input" valign="top">
        <input type="text" name="menu_title" value="<?php echo $this->menu_title?>">
      </td>
      
    </tr>
    <tr>
      <td align="right" class="form_tab_lebel" valign="top"></td>
      <td align="left" class="form_tab_input search_button" valign="top">
            <input class="search" value="Search" type="submit">
          <img class="search_img" src="<?php echo $this->cdnUri()?>/images/search_img.png" alt="">
      </td>
    </tr>
  </table>
</form>
<?php if (count($this->paginator)): ?>
<?php
$sno=0;
$page=$this->paginator->getCurrentPageNumber();
$items_per_page=$this->paginator->getItemCountPerPage(); 
if($page>1)
{
        $sno=$items_per_page*$page - $items_per_page ; 	
}
?>
<?php echo  $this->flashMessages()?>
        <?=$this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));?>
      <div class="gird_box">
        <div class="scroll-pane">
          <table style="margin: 0 0 15px 0" class="grid_table" border="0"  cellspacing="0" cellpadding="0">
            <tr>
              <th align="left" width="100"><?php echo $this->puts('S. No.');?></th>
              <th align="left" width="100"><?php echo $this->puts('Menu ID');?> <?php echo $this->sort("menu_id", $this->sortOptions);?></th>
	      <th align="left" width="250"><?php echo $this->puts('Menu Title');?> <?php echo $this->sort("menu_title", $this->sortOptions);?></th>
              <th align="left" width="300"><?php echo $this->puts('Menu Path');?></th>
              <th align="left" width="100"><?php echo $this->puts('Parent ID');?> <?php echo $this->sort("menu_parent_id", $this->sortOptions);?></th>
              <th align="left" width="100"><?php echo $this->puts('Is Active');?></th>
              <th align="left" width="100"><?php echo $this->puts('Is Child');?></th>
              <th align="left" width="100"><?php echo $this->puts('Action');?></th>	  
            </tr>
          <?php 
            foreach ($this->paginator as $item): ?>
            <?php $sno++?>
            <?php
                $menu=new Base_Security_Menu();

            ?>
            
            <tr class="package_row1">
              <td align="left"><?php echo $item['menu_sno']; ?>.</td>
              <td align="left"><?php echo $item['menu_id']; ?></td>
              <td align="left"><?php echo $item['menu_title']; ?></td>
              <td align="left"><?php echo $item['menu_path']; ?></td>
              <td align="left"><?php echo $item['menu_parent_id']; ?></td>
              
              
              
              
               <?php if( $item['menu_is_active']=="1") {
                    $title="Click here to change status";
                    $image="/images/icons/active-1.png";
                }else{
                    $image="/images/icons/deactive.png";
                    $title="Click here to change status";
                }?>
              <td align="left" class="image" id='changeStatus_<?php echo $item['menu_id']?>'><a  onclick="changeStatus(<?php echo $item['menu_id']?>, <?php echo $item['menu_is_active']?>)" href="javascript:void(0);"  title="<?php echo $title?>" ><img alt="<?php echo $title?>" src="<?php echo $image?>"/></a></td>
              <?php if( $item['menu_is_child']=="1") {
                    $title="Click here to change status";
                    $image="/images/icons/active-1.png";
                }else{
                    $title="Click here to change status";
                    $image="/images/icons/deactive.png";
                    
                }?>
              <td align="left" class="image" id='changeChildStatus_<?php echo $item['menu_id']?>'><a onclick="changeChildStatus(<?php echo $item['menu_id']?>, <?php echo $item['menu_is_child']?>)" href="javascript:void(0);" title="<?php echo $title?>" ><img alt="<?php echo $title?>" src="<?php echo $image?>"/></a></td>
              <td class="image" align="left">
                <a title="Edit" href="<?php echo $this->seoUrl("/security/menu/edit-menu-item/id/{$item['menu_id']}/guid/{$item['menu_row_guid']}")?>"><img alt="Edit" src="<?php echo $this->cdnUri()?>/images/icons/edit.png"></a>&nbsp;
                <a title="Delete" href="<?php echo $this->seoUrl("/security/menu/delete-menu-item/id/{$item['menu_id']}")?>" onclick="return confirm('Delete this item?');"><img alt="Delete" src="/images/icons/del.png"></a>
           </td> 
            </tr>
	<?php endforeach; ?>	
		
          </table>
        </div>
      </div>
      

  
    <?=$this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));?>
    







<script type="text/javascript">
    
    function changeChildStatus(menu_id, menu_is_child)
    {
        
       $("#changeChildStatus_"+menu_id).html('<img height="25px" alt="In process..." src="/images/loading.gif"/>');
       $.post(
            "/security/menu/change-child-status", 
            { 
               "id" : menu_id,
               "status" : menu_is_child
            }, 
            function (data) {
                
                if(data.result==1)
                {
                    if(menu_is_child==1)
                        menu_is_child=0;
                    else
                        menu_is_child=1;
                    
                    if( menu_is_child==1) 
                    {
                    
                        var title="Click here to change status";
                        var image="/images/icons/active-1.png";
                    }
                    else
                    {
                        var title="Click here to change status";
                        var image="/images/icons/deactive.png";
                    }
                
                    $("#changeChildStatus_"+menu_id).html('<a onclick="changeChildStatus('+ menu_id + ',' + menu_is_child + ')" href="javascript:void(0);" title="'+ title +'" ><img alt="'+ title +'" src="'+ image +'"/></a>');
                }
                    
            },"json"
        );
    }
    
    
    
    
    function changeStatus(menu_id, menu_is_active)
    {
        
       $("#changeStatus_"+menu_id).html('<img height="25px" alt="In process..." src="/images/loading.gif"/>');
       $.post(
            "/security/menu/change-status", 
            { 
               "id" : menu_id,
               "status" : menu_is_active
            }, 
            function (data) {
                
                if(data.result==1)
                {
                    if(menu_is_active==1)
                        menu_is_active=0;
                    else
                        menu_is_active=1;
                    
                    if( menu_is_active==1) 
                    {
                    
                        var title="Click here to change status";
                        var image="/images/icons/active-1.png";
                    }
                    else
                    {
                        var title="Click here to change status";
                        var image="/images/icons/deactive.png";
                    }
                
                    $("#changeStatus_"+menu_id).html('<a onclick="changeStatus('+ menu_id + ',' + menu_is_active + ')" href="javascript:void(0);" title="'+ title +'" ><img alt="'+ title +'" src="'+ image +'"/></a>');
                }
                    
            },"json"
        );
    }
    
</script>

<script type="text/javascript">
		
			
           // Script For Grid Starts //
		$(document).ready(function(){
			//row click
			$('tr.package_row1').click(function (event) {
								$('tr.package_row1').toggleClass('active', false);
								$(this).toggleClass('active', true);
								});
			// table Width
			var tblWidth=0;
			$('.grid_table tr:first').children().each(function(index) {
									tblWidth = tblWidth + parseInt($(this).attr('width'));
									});
			$(".grid_table").css("width", tblWidth);
		});

		$('.grid_table tr').find('td:last').addClass('last')
		$('.grid_table tr').find('th:last').addClass('last')
		// Script For Grid Ends //



		// Script For Scroll Panel Starts //
		$(function(){
		$('.scroll-pane').jScrollPane({showArrows: true});
		});
		// Script For Scroll Panel Ends //


		// Script For Tabs Panel Starts //
			$(function(){
				$('#tabs').tabs();
			});
		// Script For Tabs Panel Ends //
        

</script>

     
       <?php endif; ?>