<form name="create_customer">
        <div class="form_row">
          <div class="form_label">Organization Name: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" value="">
          </div>
        </div>
        <div class="form_row form_separate">
          <!-- <div class="form_label">Password: <span class="required">*</span></div>
          <div class="form_field">
            <input type="password" value="">
          </div>
          <div class="form_label">Confirm Password: <span class="required">*</span></div>
          <div class="form_field">
            <input type="password" value="">
          </div> -->
        </div>
        <!-- <div class="form_row">
          <div class="form_label">Title: <span class="required">*</span></div>
          <div class="form_field">
            <select>
              <option value="-- Select --">-- Select --</option>
            </select>
          </div>
        </div> -->
		<div class="form_row"><div class="form_label"> <h2> Shipping Address </h2></div></div>
        <div class="form_row">
          <div class="form_label">First Name: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_f_name" onkeyup="copy_shipping_to_billing(this);">
          </div>
          <div class="form_label">Last Name: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_l_name" onkeyup="copy_shipping_to_billing(this);">
          </div>
        </div>
        <!-- <div class="form_row">
          <div class="form_label">Gender: <span class="required">*</span></div>
          <div class="form_field">
            <select>
              <option value="-- Select --">-- Select --</option>
            </select>
          </div>
        </div> -->
		<div class="form_row">
          <div class="form_label">Address: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_address" onkeyup="copy_shipping_to_billing(this);">
          </div>
          <div class="form_label">City: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_city" onkeyup="copy_shipping_to_billing(this);">
          </div>
        </div>

		<div class="form_row">
          <div class="form_label">State: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_state" onkeyup="copy_shipping_to_billing(this);">
          </div>
          <div class="form_label">Zip: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_zip" onkeyup="copy_shipping_to_billing(this);">
          </div>
        </div>

        <div class="form_row">
          <div class="form_label">Phone Number: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_phone">
          </div>
          <div class="form_label">Fax: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_fax">
          </div>
        </div>

		<div class="form_row form_separate">
          <div class="form_label">Email: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="shipping_email">
          </div>
        </div>
		

		<div class="form_row"><div class="form_label"> <h2> Billing Address </h2></div></div>

		<div class="form_row"><div class="form_label"> <input type="checkbox" name="billing_shipping_same" id="billing_shipping_same" onclick="billing_shipping_same_fun(this);">Same as above </div></div>


        <div class="form_row">
          <div class="form_label">First Name: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="billing_f_name">
          </div>
          <div class="form_label">Last Name: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="billing_l_name">
          </div>
        </div>
        <!-- <div class="form_row">
          <div class="form_label">Gender: <span class="required">*</span></div>
          <div class="form_field">
            <select>
              <option value="-- Select --">-- Select --</option>
            </select>
          </div>
        </div> -->
		<div class="form_row">
          <div class="form_label">Address: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="billing_address">
          </div>
          <div class="form_label">City: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="billing_city">
          </div>
        </div>

		<div class="form_row">
          <div class="form_label">State: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="billing_state">
          </div>
          <div class="form_label">Zip: <span class="required">*</span></div>
          <div class="form_field">
            <input type="text" name="billing_zip">
          </div>
        </div>
		
        <div class="form_row">
          <div class="form_label">&nbsp;</div>
          <div class="form_field">
            <input type="button" value="Submit">
          </div>
        </div>
      </form>