<form id="login_form" action="<?php echo $this->seoUrl("/mps/auth/forgot-password")?>" method="post">
<?php if($this->msg==""){?>
    <?php echo $this->form->email;?>
    <img id='email_l' class="keyboard" src="<?php echo $this->cdnUri()?>/images/keyboard.png" alt="">
    <input id="btnLogin" name="btnLogin" type="submit" value="Submit" onclick='submitForm()'>
    
<?php }else{
?>

<span id="forget_message"><?php echo $this->msg; ?></span>

<?php
	echo "<br>";
	?>
	<div id="btnSentPassword"><input name="btnSentPassword" type="button" value="OK" onclick='submitForm()'></div>
	<?php
}
?>
    </form>
<script type="text/javascript">
    
    function submitForm()
    {
        location.href="/";
    }

$('#btnLogin').click(function() {
  $('#login_form').submit();
});
</script>





<script type="text/javascript">
//$('input[placeholder], textarea[placeholder]').placeholder();

    
    jQuery(function($) {
	
	// Username Login
	// ********************
	$('.email').keyboard({
		layout   : 'qwerty',
		 openOn : null,
         stayOpen : true,
		lockInput: true // prevent manual keyboard entry
	});
	$('#email_l').click(function(){
		$('.email').getkeyboard().reveal();
	});


	});
</script>


<script type="text/javascript">
function clearText(thefield)
{
	if (thefield.defaultValue==thefield.value)
	{
		thefield.value = "";
	}
}
function replaceText(thefield)
{
	if (thefield.value=="")
	{
		thefield.value = thefield.defaultValue;
	}
}


</script>
