<script>
  $(document).ready(function(){
    $("#addSystemMaster").validate();
  });
 </script>
  
<form id="addSystemMaster" name="addSystemMaster" action="" method="post">
<div> <?php echo $this->flashMessages()?> </div>

<div class="form_row">
    <div class="form_label">
      <?php echo $this->puts($this->form->masterCode->getLabel()); ?> <span class="required1">*</span>
    </div>
    <div class="form_field">
      <?php echo $this->form->masterCode; ?>
    </div>
	
</div>	

<div class="form_row">
    <div class="form_label">
        <?php echo $this->puts($this->form->masterValue->getLabel()); ?> <span class="required1">*</span>
    </div>
    <div class="form_field">
        <?php echo $this->form->masterValue; ?>
    </div>
    <div class="form_label">
         <?php echo $this->puts($this->form->status->getLabel()); ?> <span class="required1">*</span> 
    </div>
    <div class="form_field form_field_same">
        <?php echo $this->form->status; ?>
    </div>
    <div class="form_label addButtonRow">
        <?php if (isset($this->mode)) { ?>
        <input type="hidden" name="guid" value="<?php echo $this->escape($this->guid); ?>" />
        <input type="submit" value="Update" name="addMaster" class="addButton" />
        
        <?php } else {?>
        <input type="submit" value="Add" name="addMaster" class="addButton" />        
        <?php } ?>
        
         <?php if (isset($this->read)) { ?>
        <script>
            $(document).ready(function(){
            $("#masterCode").attr('readonly', true);   
            });
        </script>
         <?php } ?>
    </div>
</div>	



</form>
<div class="form_row form_separate">
          
        </div>
 
 
 
<?php if (count($this->paginator)): 
        $sno=0;
        $page=$this->paginator->getCurrentPageNumber();
        $items_per_page=$this->paginator->getItemCountPerPage(); 
        if($page>1)
        {
                $sno=$items_per_page*$page - $items_per_page ; 	
        }
        
            
           echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));
               
        ?>

 <div class="gird_box">
        <div class="scroll-pane">
          <table class="grid_table" border="0"  cellspacing="0" cellpadding="0" width="100%">
		  
		<tr>
                <th align="left" width="10%">ID</th>
                <th align="left" width="30%">Master Text <?php echo $this->sort("master_value",$this->sortOptions)?></th>
                <th align="left" width="10%">Is Active</th>
                <th align="left" width="10%">Action</th>
            </tr>
        <?php 
        foreach ($this->paginator as $item): ?>
        <?php $sno++?>
          
            <tr class="package_row1">
              <td align="left"><?php echo $item->master_id?>.</td>
              <td align="left"><?php echo $item->master_value;?></td>
               <td class="image" align="center" id="changeStatus_<?php echo $item->master_code;?>">
                 <?php if( $item->status=="1") {
                    $title="active!";
                    $image="/images/icons/active-1.png";
                }else{
                    $image="/images/icons/deactive.png";
                    $title="Inactive!";
                }?> 
             <img title="<?php echo $title?>" alt="<?php echo $title?>" src="<?php echo $image?>" />
            </td>              
            <td align="center">
<?php $dUrl=$this->seoUrl("/security/privilege/delete-system-master/guid/".$item->row_guid.'/masterCode/'.$item->master_code)?>                
               <a href="<?php echo $this->seoUrl("/security/privilege/add-system-master/guid/".$item->row_guid)?>"><img title="Edit" alt="Edit"src="<?php echo $this->cdnUri()?>/images/icons/edit.png" /></a>  
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void(0)" onclick="deleteMaster('<?php echo $dUrl; ?>')"><img title="Delete" alt="Delete"src="<?php echo $this->cdnUri()?>/images/del_icon.png" /></a>
               
            </td>
            </tr>
            <?php endforeach; ?>
          </table>
        </div>
      </div>
        <?php 
            
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));
            
        ?>

<?php 

endif; ?>

 
 <script type="text/javascript">

function deleteMaster(DURL)
{
    var c=confirm("Are you sure to delete");
    if (c==true)
     window.location.href=DURL;   
}
 function changeMasterStatus(row_guid,master_status)
    {
        
       $("#changeStatus_"+row_guid).html('<img height="36px" alt="In process..." src="/images/loading.gif"/>');
       $.post(
            "/security/privilege/change-status", 
            { 
               "id" : row_guid,
               "status" : master_status
            }, 
            function (data) {
                
                if(data.result==1)
                {
                    if(master_status==1)
                        master_status=0;
                    else
                        master_status=1;
                    
                    if( master_status==1) 
                    {
                    
                        var title="Click here to make inactive!";
                        var image="/images/icons/active-1.png";
                    }
                    else
                    {
                        var title="Click here to make active!";
                        var image="/images/icons/deactive.png";
                    }
                
                    $("#changeStatus_"+row_guid).html('<a onclick="changeMasterStatus(\''+ row_guid + '\',' + master_status + ')" href="javascript:void(0);" title="'+ title +'" ><img alt="'+ title +'" src="'+ image +'"/></a>');
                }
                    
            },"json"
        );
    }
		
		
        // Script For Grid Starts //
		$(document).ready(function(){
			//row click
			$('tr.package_row1').click(function (event) {
								$('tr.package_row1').toggleClass('active', false);
								$(this).toggleClass('active', true);
								});
			// table Width
			var tblWidth=0;
			$('.grid_table tr:first').children().each(function(index) {
									tblWidth = tblWidth + parseInt($(this).attr('width'));
									});
			//$(".grid_table").css("width", tblWidth);
		});

		$('.grid_table tr').find('td:last').addClass('last')
		$('.grid_table tr').find('th:last').addClass('last')
		// Script For Grid Ends //



		// Script For Scroll Panel Starts //
		$(function(){
		//$('.scroll-pane').jScrollPane({showArrows: true});
		});
		// Script For Scroll Panel Ends //


		// Script For Tabs Panel Starts //
			$(function(){
				$('#tabs').tabs();
			});
		// Script For Tabs Panel Ends //
        
     </script>
