<?php //echo $this->totalItemCount; ?>
<form method="post" action="<?php echo $this->seoUrl("/security/db-config/database-configs")?>">
    
  <table class="from_table" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="right" class="form_tab_lebel" valign="top"><?php echo $this->puts('DataBase Name');?>:</td>
    <td align="left" class="form_tab_input" valign="top"><input type="text" name="search" id="search" class="text-input small-input" value="<?php echo $this->search?>" /></td>    
    <td align="left" class="form_tab_input" valign="top"><input type="submit" class="search" value="Search"><img class="search_img" src="<?php echo $this->cdnUri()?>/images/search_img.png" alt=""></td>
  </tr>
</table>     
</form>
<?php echo  $this->flashMessages()?>

<?php if (count($this->paginator)): ?>
<?php
$sno=0;
$page=$this->paginator->getCurrentPageNumber();
$items_per_page=$this->paginator->getItemCountPerPage(); 
if($page>1)
{
        $sno=$items_per_page*$page - $items_per_page ; 	
}
?>
<?php 
    
    echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));
     
?>


    <div class="gird_box">
        <div class="scroll-pane">
          <table style="margin: 0 0 15px 0" class="grid_table" border="0"  cellspacing="0" cellpadding="0">
            <tr>
              <th align="left" width="60"><?php echo $this->puts('S. No.');?></th>
              <th align="left" width="160"><?php echo $this->puts('Config Id');?></th>
              <th align="left" width="200"><?php echo $this->puts('Server name');?></th>
              <th align="left" width="100"><?php echo $this->puts('Server port');?></th>
              <th align="left" width="150"><?php echo $this->puts('Database name');?></th>
              <th align="left" width="140"><?php echo $this->puts('Database user');?></th>
              <th align="left" width="120"><?php echo $this->puts('Transaction type');?></th>
              <th align="left" width="200"><?php echo $this->puts('Action');?></th>
            </tr>
            
            <?php 
        foreach ($this->paginator as $item): ?>
        <?php $sno++?>
          
            <tr class="package_row1">
              
            <td align="left" ><?php echo $sno?></td>
            <td align="left"><?php echo $item->config_id;?></td>
            <td  align="left"><?php echo $item->db_server_name; ?></td>
            <td align="left"><?php echo $item->db_server_port; ?></td>
            <td align="left"><?php echo $item->db_name; ?></td>
            <td align="left"><?php echo $item->db_user; ?></td>
            <td align="left"><?php echo $item->db_trans_type; ?></td>
            
             <td class="image" align="left" >
                <!-- Icons -->
                <?php if($this->checkAcl("/security/db-config/edit-config")){?>
                <a title="Edit" href="<?php echo $this->seoUrl("/security/db-config/edit-config/id/".$item->dbcnf_id)?>"><img  title="Edit" alt="Edit" src="<?php echo $this->cdnUri()?>/images/icons/edit.png"></a>
                 <?php } ?>
                 <?php 
                    $image="/images/icons/del.png";
                    $title="Click here to delete configuration!";
                ?>
               <?php if($this->checkAcl("/security/db-config/delete-config")){?>
                &nbsp;&nbsp;
                <a title="<?php echo $title?>" href="<?php echo $this->seoUrl("/security/db-config/delete-config/id/".$item->dbcnf_id)?>" onclick="javascript: return confirm('Are you sure you want to delete?');"><img alt="<?php echo $title?>"  src="<?php echo $image?>"></a> 
                 <?php } ?>
            </td>
            
      	     
            </tr>
            <?php endforeach; ?>
          </table>
        </div>
      </div>
        <?php 
         
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));
              
        ?>

<?php endif; ?>



<script type="text/javascript">
		
		
        // Script For Grid Starts //
		$(document).ready(function(){
			//row click
			$('tr.package_row1').click(function (event) {
								$('tr.package_row1').toggleClass('active', false);
								$(this).toggleClass('active', true);
								});
			// table Width
			var tblWidth=0;
			$('.grid_table tr:first').children().each(function(index) {
									tblWidth = tblWidth + parseInt($(this).attr('width'));
									});
			$(".grid_table").css("width", tblWidth);
		});

		$('.grid_table tr').find('td:last').addClass('last')
		$('.grid_table tr').find('th:last').addClass('last')
		// Script For Grid Ends //



		// Script For Scroll Panel Starts //
		$(function(){
		$('.scroll-pane').jScrollPane({showArrows: true});
		});
		// Script For Scroll Panel Ends //


		// Script For Tabs Panel Starts //
			$(function(){
				$('#tabs').tabs();
			});
		// Script For Tabs Panel Ends //
        
     </script>