<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
echo $this->form;
/*

<form id="db_create" action="<?php echo $this->seoUrl("/security/db-config/edit-config")?>" method="post">
<div> <?php echo $this->flashMessages()?> </div>
 
  
<div class="form_row">
    <div class="form_label">
      <?php echo $this->puts($this->form->configId->getLabel()); ?> <span class="required1">*</span>
    </div>
    <div class="form_field">
      <?php echo $this->form->configId; ?>
    </div>
</div>	

 <div class="form_row">	
    <div class="form_label">
      <?php echo $this->puts($this->form->dbServerName->getLabel()); ?> <span class="required1">*</span>
    </div>
    <div class="form_field">
       <?php echo $this->form->dbServerName; ?>
    </div>
</div>

 <div class="form_row">	
    <div class="form_label">
      <?php echo $this->puts($this->form->dbServerPort->getLabel()); ?>: <span class="required1">*</span>
    </div>
    <div class="form_field">
       <?php echo $this->form->dbServerPort; ?>
    </div>
</div>

<div class="form_row">	
    <div class="form_label">
      <?php echo $this->puts($this->form->dbName->getLabel()); ?> <span class="required1">*</span>
    </div>
    <div class="form_field">
      <?php echo $this->form->dbName; ?>
    </div>
</div>	

<div class="form_row">	
    <div class="form_label">
      <?php echo $this->puts($this->form->dbUser->getLabel()); ?> <span class="required1">*</span>
    </div>
    <div class="form_field">
      <?php echo $this->form->dbUser; ?>
    </div>
</div>	


<div class="form_row">	
    <div class="form_label">
      <?php echo $this->puts($this->form->dbPassword->getLabel()); ?> <span class="required1">*</span>
    </div>
    <div class="form_field">
      <?php echo $this->form->dbPassword; ?>
    </div>
</div>

<div class="form_row">	
    <div class="form_label">
      <?php echo $this->puts($this->form->dbTransType->getLabel()); ?> <span class="required1">*</span>
    </div>
    <div class="form_field">
      <?php echo $this->form->dbTransType; ?>
    </div>
</div>

<div class="form_row">	
    <div class="form_label">
      <?php echo $this->puts($this->form->status->getLabel()); ?> <span class="required1">*</span>
    </div>
    <div class="form_field">
      <?php echo $this->form->status; ?>
    </div>
</div>


<div class="form_row">  
    <div class="form_label">&nbsp;</div>
    <div class="form_field">
		<input type="submit" value="Update" name="updateDB"/>
     </div>
</div>
</form>
*/
?>
 