<?php //echo $this->totalItemCount; ?>

<form method="post" action="<?php echo $this->seoUrl("/admin/supplier/index")?>">
    
 <table class="from_table" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="right" class="form_tab_lebel" valign="top"><?php echo $this->puts("Organization Name:")?></td>
    <td align="left" class="form_tab_input" valign="top">
        <input type="text" value="<?php echo $this->search?>" name="orgName"></td>
    
    <td align="left" class="form_tab_input" valign="top"><input class="search" value="Search" type="submit" name="search"><img class="search_img" src="<?php echo $this->cdnUri()?>/images/search_img.png" alt=""></td>
  </tr>
  
</table>
    
       
</form>

<?php if (count($this->paginator)): ?>


        <?php
        $sno=0;
        $page=$this->paginator->getCurrentPageNumber();
        $items_per_page=$this->paginator->getItemCountPerPage(); 
        if($page>1)
        {
                $sno=$items_per_page*$page - $items_per_page ; 	
        }
        ?>
        <?php 
           
           echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));
              
        ?>
<div> <?php echo $this->flashMessages()?> </div>


    <div class="gird_box">
        <div class="scroll-pane">
          <table style="margin: 0 0 15px 0" class="grid_table" border="0"  cellspacing="0" cellpadding="0">
            <tr>
              <th align="left" width="35"><?php echo $this->puts("S.No.")?></th>
              <th align="left" width="250"><?php echo $this->puts("Organization Name")?></th>
              <th align="left" width="130"><?php echo $this->puts("First Name")?></th>
              <th align="left" width="130"><?php echo $this->puts("Last Name")?></th>
              <th align="left" width="180"><?php echo $this->puts("Address")?></th>
              <th align="left" width="110"><?php echo $this->puts("City")?><?php echo $this->sort("city", $this->sortOptions);?></th>
              <th align="left" width="110"><?php echo $this->puts("State")?><?php echo $this->sort("state", $this->sortOptions);?></th>
              <th align="left" width="100"><?php echo $this->puts("Zip")?><?php echo $this->sort("zip", $this->sortOptions);?></th>
              <th align="left" width="100"><?php echo $this->puts("Phone")?></th>
              <th align="left" width="100"><?php echo $this->puts("Fax")?></th>
              <th align="left" width="150"><?php echo $this->puts("Email")?></th>
              <th align="left" width="15%"><?php echo $this->puts("Is Active")?></th>
              <th align="left" width="120"><?php echo $this->puts("Action")?></th>
            </tr>
            
            <?php 
        foreach ($this->paginator as $item): ?>
        <?php $sno++?>
          
            <tr class="package_row1">
              <td align="left"><?php echo $sno?>.</td>
              <td align="left"><?php echo $item->org_name;?></td>
              <td align="left"><?php echo $item->first_name;?></td>
              <td align="left"><?php echo $item->last_name;?></td>
              <td align="left"><?php echo $item->address1;?></td>
              <td align="left"><?php echo $item->city;?></td>
              <td align="left"><?php echo $item->state;?></td>
              <td align="left"><?php echo $item->zip;?></td>
              <td align="left"><?php echo $item->phone;?></td>
              <td align="left"><?php echo $item->fax;?></td>
              <td align="left"><?php echo $item->email;?></td>
              <?php if( $item->status=="1") {
                    $title="Click here to make product inactive!";
                    $image="/images/icons/active-1.png";
                }else{
                    $image="/images/icons/deactive.png";
                    $title="Click here to make product active!";
                }?>
              <td align="left" class="image" id='changeStatus_<?php echo $item->id ?>'>
               <?php if($this->checkAcl("/admin/supplier/change-status")){?>   
                  <a  onclick="changeStatus(<?php echo $item->id ?>, <?php echo $item->status ?>)" href="javascript:void(0);"  title="<?php echo $title?>" ><img alt="<?php echo $title?>" src="<?php echo $image?>"/></a>
              <?php } ?>
              </td>
              
              <td class="image" align="left">
                  
               <?php if($this->checkAcl("/admin/supplier/edit-supplier")){?>   
                  <a href="<?php echo $this->seoUrl("/admin/supplier/edit-supplier/id/".$item->id."/guid/".$item->row_guid) ?>"><img title="Edit" alt="Edit"src="<?php echo $this->cdnUri()?>/images/icons/edit.png" /></a>  
               <?php } ?>
            </td>
           
            </tr>
            <?php endforeach; ?>
          </table>
        </div>
      </div>
        <?php 
           
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));
               
        ?>

<?php endif; ?>










<script type="text/javascript">
		
	

    function changeStatus(menu_id, menu_is_active)
    {
        
       $("#changeStatus_"+menu_id).html('<img height="25px" alt="In process..." src="/images/loading.gif"/>');
       $.post(
            "/admin/supplier/change-status", 
            { 
               "id" : menu_id,
               "status" : menu_is_active
            }, 
            function (data) {
                
                if(data.result==1)
                {
                    if(menu_is_active==1)
                        menu_is_active=0;
                    else
                        menu_is_active=1;
                    
                    if( menu_is_active==1) 
                    {
                    
                        var title="Click here to change status";
                        var image="/images/icons/active-1.png";
                    }
                    else
                    {
                        var title="Click here to change status";
                        var image="/images/icons/deactive.png";
                    }
                
                    $("#changeStatus_"+menu_id).html('<a onclick="changeStatus('+ menu_id + ',' + menu_is_active + ')" href="javascript:void(0);" title="'+ title +'" ><img alt="'+ title +'" src="'+ image +'"/></a>');
                }
                    
            },"json"
        );
    }
    
    
        // Script For Grid Starts //
		$(document).ready(function(){
			//row click
			$('tr.package_row1').click(function (event) {
								$('tr.package_row1').toggleClass('active', false);
								$(this).toggleClass('active', true);
								});
			// table Width
			var tblWidth=0;
			$('.grid_table tr:first').children().each(function(index) {
									tblWidth = tblWidth + parseInt($(this).attr('width'));
									});
			$(".grid_table").css("width", tblWidth);
		});

		$('.grid_table tr').find('td:last').addClass('last')
		$('.grid_table tr').find('th:last').addClass('last')
		// Script For Grid Ends //



		// Script For Scroll Panel Starts //
		$(function(){
		$('.scroll-pane').jScrollPane({showArrows: true});
		});
		// Script For Scroll Panel Ends //


		// Script For Tabs Panel Starts //
			$(function(){
				$('#tabs').tabs();
			});
		// Script For Tabs Panel Ends //
        
     </script>
