<?php echo  $this->flashMessages()?>

<form method="post" >
  
  
  <div class="form_row">
    <div class="form_label">
      <?php echo $this->puts($this->form->workflowName->getLabel()); ?> <span class="required">*</span>
    </div>
    <div class="form_field">
      <?php echo $this->form->workflowName; ?>
        </div>
  </div>
  

    
  <div class="form_row">
    <div class="form_label">&nbsp;</div>
    <div class="form_field">
            <?php echo $this->form->submit;?>
      
        </div>
  </div>
  
</form>