<script>
  $(document).ready(function(){
    $("#location_create").validate();
  });
 </script>
  
<form id="location_create" action="" method="post">
	<div> <?php echo $this->flashMessages()?> </div>
	 
	  
	<div class="form_row">
		<div class="form_label">
		  <?php echo $this->puts($this->form->title->getLabel()); ?> <span class="required1">*</span>
		</div>
		<div class="form_field">
		  <?php echo $this->form->title; ?>
		</div>
	</div>	

	 <div class="form_row">	
		<div class="form_label">
		  <?php echo $this->puts($this->form->description->getLabel()); ?> <span class="required1">*</span>
		</div>
		<div class="form_field">
		   <?php echo $this->form->description; ?>
		</div>
	</div>

	 <div class="form_row">	
		<div class="form_label">
		  <?php echo $this->puts($this->form->weight->getLabel()); ?>: <span class="required1">*</span>
		</div>
		<div class="form_field">
		   <?php echo $this->form->weight; ?>
		</div>
	</div>


	<div class="form_row">
		<div class="form_label"><?php echo $this->puts($this->form->status->getLabel());?></div>
		<div class="form_field_same"><?php echo $this->form->status?></div>
	</div>

	<div class="form_row">  
		<div class="form_label"><input type="hidden" name="guid" 
		value="<?php echo $this->escape($this->guid); ?>"></div>
		<div class="form_field">
			<input type="submit" value="Submit" name="addLocation">
		 </div>
	</div>
</form>