<footer>
<!--  <ul>
    <li><a href="#">Manage Staff</a></li>
    <li><a href="#">Manage Suppliers</a></li>
    <li><a href="#">Manage Customers</a></li>
    <li><a href="#">Manage Products</a></li>
    <li><a href="#">Manage Cow Profile</a></li>
    <li><a href="#">Manage Inventory Location</a></li>
    <li><a href="#">Manage Lot Price</a></li>
    <li><a href="#">Group/Role Setup</a></li>
    <li><a href="#">Permission Setup</a></li>
    <li><a href="#">Logout</a></li>
  </ul>-->
  <p>Copyright &copy; 2012 Dale T.Smith &amp; Sons. All Rights Reserved.</p>
  <ul>
    <li><a href="<?php echo $this->seoUrl("/mps/app/disclaimer")?>">Disclaimer</a></li><li style="background: none repeat scroll 0% 0% transparent;"><a href="<?php echo $this->seoUrl("/mps/app/terms-and-conditions")?>">Terms and Conditions</a></li></ul>
</footer>
<script>
$('input[placeholder], textarea[placeholder]').placeholder();
</script>