<section id="sidebar" class="left_section">

<div id="main-nav"> 

<?php

foreach ($this->container as $page)
{
     if ($page->isVisible() && $this->navigation()->accept($page)) 
     {
        ?>
            <ul><li class="section-header"><?php echo $this->puts($page->getLabel())?>
        <?
         foreach ($page as $p)
         {
             
             if ($p->isVisible() && $this->navigation()->accept($p)) 
             {
                 $isActive = $p->isActive(true);
                 $activeClass = $isActive ? ' current"' : '';
                ?>
                <li>
                    <a href="<?php if(count($p)>0){?>#<?php }else {echo $this->seoUrl($p->getHref());}?>" class="nav-top-item <?php if(count($p)==0){?>no-submenu<?php }?> <?php echo $activeClass?>"><?php echo $this->puts($p->getLabel())?></a>

                    <?php  
                    if(count($p)>0)
                    {
                        ?>
                        <ul >
                        <?php
                        
                            foreach ($p as $_p)
                            {   
                                if ($_p->isVisible() && $this->navigation()->accept($_p)) 
                                {
                                    $isActive = $_p->isActive(true);
                                    $activeClass = $isActive ? ' current' : ' ';
                                ?>  
                                    <li><a class="<?php echo $activeClass?>" href="<?php echo  $this->seoUrl($_p->getHref())?>"><?php echo $this->puts($_p->getLabel())?></a></li>
                                <?php 

                                }//end if
                            }
                        
                        ?>
                        </ul>
                        <?php
                    }
                    ?>
                </li>

                <?php
             }//end if
             
           
         }
          ?>
            </li></ul>
          <? 
     }//end if
}

?>
                
</div>

    </section>

