<?php
$this->headScript()->appendFile("/js/ui.dropdownchecklist-1.4-min.js");
$this->headScript()->appendFile("/js/ui.dropdownchecklist.js");
//$this->headScript()->appendFile("/js/jquery-1.6.1.min.js");
$this->headScript()->appendFile("/js/jquery-ui-1.8.13.custom.min.js");
$this->headLink()->appendStylesheet('/js/ui.dropdownchecklist.standalone.css');
$this->headLink()->appendStylesheet('/js/ui.dropdownchecklist.themeroller.css');
$this->headLink()->appendStylesheet('/js/smoothness-1.8.13/jquery-ui-1.8.13.custom.css');
?>

      <form method="post" action="<?php echo $this->seoUrl("/admin/product/index")?>">
        <table class="from_table" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td align="right" class="form_tab_lebel" valign="top"><?php echo $this->puts('Product ID');?>:</td>
            <td align="left" class="form_tab_input" valign="top">
              <?php echo $this->form->productIdentifier; ?>
            </td>
            <td align="right" class="form_tab_lebel" valign="top"><?php echo $this->puts('Product Name');?>:</td>
            <td align="left" class="form_tab_input" valign="top">
              <?php echo $this->form->labelCase; ?>
            </td>
            <td align="right"  class="form_tab_lebel" valign="top"><?php echo $this->puts($this->form->packLocation->getLabel()); ?></td>
            <td align="left" class="form_tab_input" valign="top">
		<?php echo $this->form->packLocation; ?>          
            </td>
          </tr>
          <tr>
            <td align="right" class="form_tab_lebel" valign="top"></td>
            <td align="left" class="form_tab_input search_button" valign="top">
              <input class="search" value="Search" type="submit"><img class="search_img" src="<?php echo $this->cdnUri()?>/images/search_img.png" alt=""></td>
            <td align="right"  class="form_tab_lebel" valign="top"></td>

          </tr>
        </table>
      </form>
<?php if (count($this->paginator)): ?>


        <?php
        $sno=0;
        $page=$this->paginator->getCurrentPageNumber();
        $items_per_page=$this->paginator->getItemCountPerPage(); 
        if($page>1)
        {
                $sno=$items_per_page*$page - $items_per_page ; 	
        }
        ?>
        <?php 
         
           echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));
             
        ?>
<div> <?php echo $this->flashMessages()?> </div>
      <div class="gird_box">
        <div class="scroll-pane">
          <table width="100%" class="grid_table" border="0" cellpadding="0" cellspacing="0">
            <tbody>
              <tr>
              <th align="left" width="8%"><?php echo $this->puts('Product ID');?></th>
              <th align="left" width="12%"><?php echo $this->puts('Product Name');?></th>
              <th align="left" width="12%"><?php echo $this->puts('Pack Location')?> <?php echo $this->sort("pack_location", $this->sortOptions);?></th>
                <th align="left" width="12%"><?php echo $this->puts('Case Format');?></th>
                <!--<th align="left" width="12%">Part Number</th>
                <th align="left" width="12%">Sell By Days</th>
                <th align="left" width="12%">Price/lb ($)</th>-->
                <th align="left" width="15%"><?php echo $this->puts('Is Active');?></th>
                <th width="8%" align="left"><?php echo $this->puts('Action');?></th>
            </tr>
           <?php 
        foreach ($this->paginator as $item): ?>
        <?php $sno++?>
            <tr class="package_row1">
              <td align="left"><?php echo $item->product_identifier;?></td>
              <td align="left"><?php echo $item->label_case;?></td>
              <?php 
              $pack_location_arr = explode(',',$item->pack_location);
              $p_count = count($pack_location_arr);
              $Locationobj = new Admin_Model_Location();
              $pack_loca_final = '';
              while($p_count>0){
                $p_id = $p_count - 1;
                
                $where = "id = '$pack_location_arr[$p_id]'";
               
                $res = $Locationobj->fetchRow($where);
               
                $pack_loca_final .= $res -> title.',';
                $p_count--;
              }
              $pack_loca_final = substr($pack_loca_final , 0 , strlen($pack_loca_final)-1);
             
              ?>
              <td align="left"><?php echo $pack_loca_final;?></td>
              <td align="left"><?php echo $item->case_format;?></td>
              <?php if( $item->status=="1") {
                    $title="Click here to make product inactive!";
                    $image="/images/icons/active-1.png";
                }else{
                    $image="/images/icons/deactive.png";
                    $title="Click here to make product active!";
                }?>
              <td align="left" class="image" id='changeStatus_<?php echo $item->id ?>'>
                <?php if($this->checkAcl("/admin/product/change-status")){?>  
                  <a  onclick="changeStatus(<?php echo $item->id ?>, <?php echo $item->status ?>)" href="javascript:void(0);"  title="<?php echo $title?>" ><img alt="<?php echo $title?>" src="<?php echo $image?>"/></a>
              <?php } ?>
              </td>
              
              <td align="left" class="image">
                 <?php if($this->checkAcl("/admin/product/edit-product")){?>   
                  <a href="<?php echo $this->seoUrl("/admin/product/edit-product/id/".$item->id."/guid/".$item->row_guid) ?>"><img title="Edit" alt="Edit" src="<?php echo $this->cdnUri()?>/images/icons/edit.png" /></a>  
                  <?php } ?>
                  
              </td>
            </tr>
            		
            <?php endforeach; ?>

          </tbody></table>
        </div>
      </div>
       <?php 
            
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-ext.phtml',array("linkArray"=>$this->linkArray));
             
        ?>

<?php endif; ?>
     <script type="text/javascript">
		
	function changeStatus(menu_id, menu_is_active)
    {
        
       $("#changeStatus_"+menu_id).html('<img height="25px" alt="In process..." src="/images/loading.gif"/>');
       $.post(
            "/admin/product/change-status", 
            { 
               "id" : menu_id,
               "status" : menu_is_active
            }, 
            function (data) {
                
                if(data.result==1)
                {
                    if(menu_is_active==1)
                        menu_is_active=0;
                    else
                        menu_is_active=1;
                    
                    if( menu_is_active==1) 
                    {
                    
                        var title="Click here to change status";
                        var image="/images/icons/active-1.png";
                    }
                    else
                    {
                        var title="Click here to change status";
                        var image="/images/icons/deactive.png";
                    }
                
                    $("#changeStatus_"+menu_id).html('<a onclick="changeStatus('+ menu_id + ',' + menu_is_active + ')" href="javascript:void(0);" title="'+ title +'" ><img alt="'+ title +'" src="'+ image +'"/></a>');
                }
                    
            },"json"
        );
    }
    
    
        // Script For Grid Starts //
		$(document).ready(function(){
			//row click
			$('tr.package_row1').click(function (event) {
								$('tr.package_row1').toggleClass('active', false);
								$(this).toggleClass('active', true);
								});
			// table Width
			var tblWidth=0;
			$('.grid_table tr:first').children().each(function(index) {
									tblWidth = tblWidth + parseInt($(this).attr('width'));
									});
		//	$(".grid_table").css("width", tblWidth);
		});

		$('.grid_table tr').find('td:last').addClass('last')
		$('.grid_table tr').find('th:last').addClass('last')
		// Script For Grid Ends //



		// Script For Scroll Panel Starts //
		$(function(){
		//$('.scroll-pane').jScrollPane({showArrows: true});
		});
		// Script For Scroll Panel Ends //


		// Script For Tabs Panel Starts //
			$(function(){
				$('#tabs').tabs();
			});
		// Script For Tabs Panel Ends //
        
     </script>

            <script type="text/javascript">

		$(".s1").dropdownchecklist({ emptyText: "Please select ...", width: 110 });
                //$(".s1").dropdownchecklist({ firstItemChecksAll: true, explicitClose: '...close' , width: 110 }); //Jitendra
                
     </script>