<form id="db_create" action="<?php echo $this->postUrl?>" method="post">
<div> <?php echo $this->flashMessages()?> </div>
 
  
<div class="form_row">
    <div class="form_label">
      <?php echo $this->puts($this->form->categoryId->getLabel()); ?> 
    </div>
    <div class="form_field">
      <?php echo $this->form->categoryId; ?>
    </div>
</div>	

 <div class="form_row">	
    <div class="form_label">
      <?php echo $this->puts($this->form->severityId->getLabel()); ?> <span class="required1">*</span>
    </div>
    <div class="form_field">
       <?php echo $this->form->severityId; ?>
    </div>
</div>

 <div class="form_row">	
    <div class="form_label">
      <?php echo $this->puts($this->form->typeId->getLabel()); ?> 
    </div>
    <div class="form_field">
       <?php echo $this->form->typeId; ?>
    </div>
</div>



<div class="form_row">	
    <div class="form_label">
      <?php echo $this->puts($this->form->userMessage->getLabel()); ?> 
    </div>
    <div class="form_field">
      <?php echo $this->form->userMessage; ?>
    </div>
</div>	
	
<div class="form_row">	
    <div class="form_label">
      <?php echo $this->puts($this->form->sysMessage->getLabel()); ?> 
    </div>
    <div class="form_field">
      <?php echo $this->form->sysMessage; ?>
    </div>
</div>	


<div class="form_row">  
    <div class="form_label">&nbsp;</div>
    <div class="form_field">
		<?php echo $this->form->submit; ?>
     </div>
</div>
</form>