<script>
  $(document).ready(function(){
    $("#create_customer").validate({});
    $("#sameBilling").attr("checked", false);
    
  });
 </script>
<script type="text/javascript">
function billing_shipping_same_fun(obj){
	var form_dom = document.create_customer;
	if(obj.checked == true){
		form_dom.bFirstName.value = form_dom.firstName.value;
		form_dom.bLastName.value = form_dom.lastName.value;
		form_dom.bAddress.value = form_dom.address.value;
		form_dom.bCity.value = form_dom.city.value;
		form_dom.bState.value = form_dom.state.value;
		form_dom.bZip.value = form_dom.zip.value;
                $(".billingAddress").hide();
                $("#bottomRow").removeClass("form_separate");
                
	}
	else{
		form_dom.bFirstName.value = '';
		form_dom.bLastName.value = '';
		form_dom.bAddress.value = '';
		form_dom.bCity.value = '';
		form_dom.bState.value = '';
		form_dom.bZip.value = '';
                $(".billingAddress").fadeIn(500);
                $("#bottomRow").addClass("form_separate");
                
	}
}

function copy_shipping_to_billing(obj){

	var form_dom = document.create_customer;
        
        //alert (form_dom[10].checked);
	if(form_dom[10].checked == true){
		switch(obj.name){
		case 'firstName':
			form_dom.bFirstName.value = form_dom.firstName.value;
			break;
		case 'lastName':
			form_dom.bLastName.value = form_dom.lastName.value;
			break;
		case 'address':
			form_dom.bAddress.value = form_dom.address.value;
			break;
		case 'city':
			form_dom.bCity.value = form_dom.city.value;
			break;
		case 'state':
			form_dom.bState.value = form_dom.state.value;
			break;
		case 'zip':
			form_dom.bZip.value = form_dom.zip.value;
			break;
		}
	}
}
</script>

<form id="create_customer" name="create_customer" action="" method="post">
    <div> <?php echo $this->flashMessages()?> </div>
        <div class="form_row">
          <div class="form_label">
              <?php echo $this->puts($this->form->orgName->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
            <?php echo $this->form->orgName; ?>
          </div>
        </div>
        <div class="form_row form_separate">
          
        </div>
        
<div class="form_row"><div class="form_label"> <h2> <?php echo $this->puts('Shipping Address');?> </h2></div></div>
        <div class="form_row">
          <div class="form_label">
              <?php echo $this->puts($this->form->firstName->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
              <?php echo $this->form->firstName; ?>
            
          </div>
          <div class="form_label">
              <?php echo $this->puts($this->form->lastName->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
              <?php echo $this->form->lastName; ?> 
            
          </div>
        </div>
        
	<div class="form_row">
          <div class="form_label">
              <?php echo $this->puts($this->form->address->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
              <?php echo $this->form->address; ?> 
            
          </div>
          <div class="form_label">
              <?php echo $this->puts($this->form->city->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
              <?php echo $this->form->city; ?> 
            
          </div>
        </div>

		<div class="form_row">
          <div class="form_label">
              <?php echo $this->puts($this->form->state->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
              <?php echo $this->form->state; ?> 
            
          </div>
          <div class="form_label">
              <?php echo $this->puts($this->form->zip->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
              <?php echo $this->form->zip; ?> 
            
          </div>
        </div>

        <div class="form_row">
          <div class="form_label">
              <?php echo $this->puts($this->form->phone->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
            <?php echo $this->form->phone; ?>
          </div>
          <div class="form_label">
              <?php echo $this->puts($this->form->fax->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
            <?php echo $this->form->fax; ?> 
          </div>
        </div>

	<div class="form_row">
          <div class="form_label">
              <?php echo $this->puts($this->form->email->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
            <?php echo $this->form->email; ?> 
          </div>
        </div>

	<div class="form_row form_separate" id="bottomRow">
          <div class="form_label">
              <?php echo $this->puts($this->form->sameBilling->getLabel()); ?> <span class="required1">*</span>
          </div>
            
          <div class="form_field_same">
              <?php echo $this->form->sameBilling; ?>
           
              &nbsp;&nbsp;Same as Above </div>
        </div>

 <div class="billingAddress">			
	 <div class="form_row"><div class="form_label"> <h2> <?php echo $this->puts('Billing Address');?> </h2></div></div>

	 <div class="form_row">
          <div class="form_label">
              <?php echo $this->puts($this->form->bFirstName->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
            <?php echo $this->form->bFirstName; ?> 
          </div>
          <div class="form_label">
              <?php echo $this->puts($this->form->bLastName->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
            <?php echo $this->form->bLastName; ?> 
          </div>
        </div>
        
         <div class="form_row">
          <div class="form_label">
              <?php echo $this->puts($this->form->bAddress->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
            <?php echo $this->form->bAddress; ?> 
          </div>
          <div class="form_label">
              <?php echo $this->puts($this->form->bCity->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
            <?php echo $this->form->bCity; ?> 
          </div>
        </div>

		<div class="form_row">
          <div class="form_label">
              <?php echo $this->puts($this->form->bState->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
            <?php echo $this->form->bState; ?> 
          </div>
          <div class="form_label">
              <?php echo $this->puts($this->form->bZip->getLabel()); ?> <span class="required1">*</span>
          </div>
          <div class="form_field">
            <?php echo $this->form->bZip; ?> 
          </div>
        </div>
 </div>
        <div class="form_row">
          <div class="form_label">&nbsp;</div>
          <div class="form_field">
            <input type="submit" value="Submit" name="submit"/>
          </div>
        </div>
      </form>